.github/workflows/integration_tests.yml
integration_tests/run.sh
integration_tests/serverless.yml
scripts/build_binary_and_layer.sh
scripts/publish_prod.sh

Build script:
- **Remove COMPRESS option** - We no longer want to compress the extension binary because we found it causes a significant performance penalty on cold starts. The old option also removed the symbol tables from the binary with the `-ldflags="-s -w"` option. We will now do this for all builds (production and sandbox) for consistency.
- **Inject the current extension version number into the binary** - This is achieved using another `ldflags` option. I will open another PR in the datadog-agent repository that adds this version number to all telemetry from the Lambda extension.
Integration tests:
- Mask extension version numbers in the snapshots so that they will be consistent from execution to execution. The new snapshots with the version numbers are not present in this pull …

Remove compress option, inject version number, and other miscellaney

---

integration_tests/run.sh

This will allow the integration tests to correctly mask the `dd_extension_version` tag.

Change `extension_version` tag key to `dd_extension_version`

---

scripts/publish_sandbox.sh

- Move into the correct directory to use the `publish_sandbox` script
- Do not sign the layer when publishing to the sandbox AWS account. Signing the layer is time-consuming, requires an additional MFA token, and it not needed when testing in the sandbox account.

Fix and speed up publish_sandbox

---

scripts/build_binary_and_layer_dockerized.sh

We should be able to run `build_binary_and_layer_dockerized` from any directory. This will allow us to move the integration tests to the agent repository while leaving other scripts in this repository. The integration test script in the other repository will be able to use this build script.

Allow builds from any directory

---

scripts/Dockerfile.build
scripts/boot.sh

This PR adds the bootstrap script (referenced by `AWS_LAMBDA_EXEC_WRAPPER`) to enable the proxy.
This script is embed at the root level of the extension layer `/opt`

Add bootstrap script for proxy

---

scripts/boot.sh

Right now the bootstrap script always logs debug information. We should only do this if DD_LOG_LEVEL is set to DEBUG.

Do not log from bootstrap script unless DD_LOG_LEVEL is DEBUG

---

scripts/publish_sandbox.sh

Allows us to publish release candidates to the `us-east-1` region

Add release candidate option to publish_sandbox

---

scripts/publish_sandbox.sh

Increment the version of the release candidate by one; don't use the version number from sa-east-1.

Fix bug in publish_sandbox for release candidates

---

scripts/Dockerfile.build

Since the agent is now built with 1.17 (https://github.com/DataDog/datadog-agent/pull/10689/files) this PR bumps our building image

Bump the builder docker image to go 1.17

---

scripts/Dockerfile.race.build
scripts/build_binary_and_layer_dockerized.sh

Created a secondary docker file, `Docker.race.build`, that will be used when `RACE_DETECTION_ENABLED` is set as `true`. It can be enabled with integration tests from the agent repo or when running the binary and layer build script individually.

Add the option to use go -race 

---

scripts/Dockerfile.build
scripts/build_binary_and_layer_dockerized.sh

Since Docker `18.09` Buildx is bundled with Docker (Source : https://docs.docker.com/develop/develop-images/build_enhancements/)

Remove buildx (now integrated with Docker)

---

scripts/Dockerfile.build

make boot.sh executable
(integration test are now passing with this branch here : https://github.com/DataDog/datadog-agent/pull/11831)

make boot.sh executable

---

scripts/publish_layers.sh

Pass arm64 or x86_64 to the compatible architectures flag, to prevent inadvertently instrumenting functions with the wrong architecture version of the extension.

feat: pass compatible architectures

---

scripts/datadog_wrapper

This PR adds `DD_RUNTIME_METRICS_ENABLED` and set it to `false` to prevent any conflict between the extension dogstatsd server and the java tracer one.
Tests:
- Using `load-test-extension-checker` dashboard, we can now see 100% of the enhanced metrics being sent.
- No more `com.timgroup.statsd.StatsDClientException: Failed to start StatsD client` could be found in logs

Fix metric data loss from Java universal instrumentation 

---

scripts/datadog_wrapper

What does this PR do?
To search .NET profiler from all possible directories.
The new dd-extension will support .NET running on arm64, while the profiler file may reside in a new different directory other than before.
This PR is to handle such scenario.
Motivation:
https://datadoghq.atlassian.net/browse/SLS-2190
Describe how to test/QA your changes
Manual e2e test

To find dotNet profilers from all possible directories

---

local_tests/build-docker-python.sh

For those using the new M1 macbooks, the extension and layer must be built with `arm64` architecture instead of `amd64`. We can determine this dynamically using the `uname -m` command which will return `arm64` if on an M1.
Note I have not tested this on a non M1 computer. I would like to ask someone to do this before I merge.

Build docker image using arm64 when on an M1 chip.

---

local_tests/build-docker-python.sh

This was erroneous removed as part of https://github.com/DataDog/datadog-lambda-extension/pull/73. Without this variable the `scripts/build_binary_and_layer_dockerized.sh` script will always build for both `arm64` and `amd64`.

Pass architecture to build script.

---

scripts/publish_layers.sh
scripts/publish_sandbox.sh

This PR is a redux of https://github.com/DataDog/datadog-lambda-extension/pull/26/files, but basically just adds a SUFFIX to layer names. Usage is like so:
`SUFFIX=aj-`
thus:

feat: custom layer names

---

build-tools/Cargo.lock
build-tools/Cargo.toml
build-tools/Dockerfile
build-tools/src/commands/common.rs
build-tools/src/commands/deploy_command.rs
build-tools/src/commands/deploy_function_command.rs
build-tools/src/commands/invoke_function_command.rs
build-tools/src/commands/list_region_command.rs
build-tools/src/commands/mod.rs
build-tools/src/commands/sign_command.rs
build-tools/src/main.rs
build-tools/src/security.rs

- Add a `deploy_function` command
- Update the `key` parameter for an optional one
Indeed when we want to deploy a layer in a non-matrixed job, there is no need to share credentials, we could use env variable directly
This feature is used in the POC to computed cold start duration for each PR in dd-trace-*

[build tools] deploy + invoke function commands

---

scripts/Dockerfile.alpine.build
scripts/Dockerfile.build
scripts/Dockerfile.race.build
scripts/build_binary_and_layer_dockerized.sh
scripts_v2/Dockerfile.build

Enabling OTLP endpoints in the lambda extension will require us to include the go build tag `"otlp"`. This pull request adds this tag when building `cmd/serverless` but not when building `cmd/serverless-init`.

Build binaries with otlp enabled.

---

scripts/datadog_wrapper

From testing, it appears using the wrapper script was causing the JAVA_TOOLS_OPTIONS to be partially ignored. When launching Java, the Lambda runtime uses the following args:
```
/var/lang/bin/java -XX:MaxHeapSize=222823k -XX:MaxMetaspaceSize=26214k -XX:ReservedCodeCacheSize=13107k -XX:+UseSerialGC -javaagent:/var/runtime/amzn-log4j-security-jdk11-0.1alpha.jar -XX:-TieredCompilation -Djava.net.preferIPv4Stack=true -Dorg.crac.Core.Compat=org.crac.inmemory -classpath /var/runtime/lib/aws-lambda-java-core-1.2.0.jar:/var/runtime/lib/aws-lambda-java-runtime-0.2.0.jar:/var/runtime/lib/aws-lambda-java-serialization-0.2.0.jar:/var/runtime/lib/org-crac-inmemory-0.1.0.jar lambdainternal.AWSLambda
```
The -XX:-TieredCompilation was conflicting with our '-XX:+TieredCompilation' setting, …

Add performance optimization for Java

---

scripts/publish_prod.sh

The workaround solution for `Error authenticating to IdP.: page is missing saml assertion` issue when deploying to GovCloud.
https://datadoghq.atlassian.net/wiki/spaces/ENG/pages/1842709292/US1-Fed+Access#CLI%2FTerraform-Access

Use ddsaml2aws to deploy to avoid Error authenticating to IdP. 

---

scripts/Dockerfile.build
scripts/Dockerfile.race.build
scripts/build_binary_and_layer_dockerized.sh
scripts/visualize_size.sh

This pull request updates the `scripts/visualize_size.sh` to include several more helpful tools. See the help menu included in the script for more details on each of these.
Also added is a `BUILD_TAGS` variable which allows for configuration of the go build tags used when building the extension. It defaults to `serverless`, so by default the build script will act just as it did before this change.

Tools for visualizing the size of the extension.

---

scripts/build_binary_and_layer_dockerized.sh

Only set the `BUILD_TAGS` variable if it is not already set. This makes it easier to do local testing with different build tags.
Note this only impacts the original v1 scripts. The scripts used by the github action can already handle non-default build tags.

Allow for setting non-default build tags.

---

scripts/Dockerfile.alpine.build
scripts/build_binary_and_layer_dockerized.sh
scripts/build_cloud_run.sh

- Fix cloud run build script (go 1.19)
- Propagate AGENT_VERSION variable
- Don't build serverless-init for arm64 arch

Fix cloud run build script (go 1.19)

---

scripts/Dockerfile.build
scripts_v2/Dockerfile.build

This PR fixes the SHA1 for golang 1.19 to make sure glibc version is still compatible with lambda

fix golang sha1

---

scripts/Dockerfile.build
scripts_v2/Dockerfile.build

https://github.com/DataDog/datadog-lambda-extension/pull/145 introduced an issue where the SHA1 specified is no more compatible with multi-arch docker
This PRs use the AWS Lambda provided image + install go lang to avoid any issue with GLIBC + respect the multi arch

Fix ARM build

---

.github/workflows/release-serverless-init.yml
scripts/Dockerfile.serverless-init.alpine.build
scripts/Dockerfile.serverless-init.build
scripts/build_binary_and_layer_dockerized.sh
scripts/build_serverless_init.sh

This PR adds a new Github action to deploy datadog/serverless-init:${tag} and serverless-init:${tag}-alpine to Dockerhub. This PR also introduces two new secrets: DOCKER_USERNAME and DOCKER_TOKEN.

Adds a manual dispatch action to deploy serverless-init

---

scripts/Dockerfile.build
scripts_v2/Dockerfile.build

Due to the fact that the base image changed lately, the cache location has also moved.
This PR fixes this location to speed up drastically the build time

fix cache while building the image

---

.github/workflows/release-serverless-init.yml
.gitlab-ci.yml

It's easier to use GHCR as we don't need to manage credentials, and we're replicating to Dockerhub, ECR, and GCR anyways. This makes GHCR the source of truth, and provides clear separation as to which registry is responsible for what.

Switch serverless-init deployments to use GHCR instead of Dockerhub

---

scripts/datadog_wrapper

This PR updates the paths used in the `datadog_wrapper` script to discover the .NET tracer's libraries.
Try these paths, in order:
- the shared loader
- the tracer stand-alone library
- an older path for backwards compat with very old .NET tracer layers

update paths to .NET tracer libs

---

.github/workflows/release-serverless-init.yml

The build script takes this as an argument, which we weren't setting.

Add architecture to deploy script

---

scripts/datadog_wrapper

Adds a check for the DD trace agent .jar prior to disabling runtime metrics. More specific to those instrumenting their container image Lambda functions, since the `AWS_EXECUTION_ENV` environment variable is not immediately identifiable as Java.
We had a support case where this specific issue came up, causing runtime metrics to be enabled and thus timing out the DD Extension's/agent's metric forwarder.

[SLES-1145] Check if the Java trace agent jar is present

---

.github/workflows/release-serverless-init.yml

Docker buildx images are failing to push to GCR with provenance set to true. Starting in build-and-push action v3, this setting defaults to true. Set it to false so we can push to GCR.
[Github issue](https://github.com/docker/buildx/issues/1513)
After this fix, pushing works, and all image manifests are the same.

Set provenance to false by default

---

scripts/publish_sandbox.sh

Use sso instead of regular account to publish scripts as we're going to be migrating to SSO.

Use sso for sandbox publishing script

---

README.md

While testing the changes I made for [this Jira task](https://datadoghq.atlassian.net/browse/AIT-8382), I had to follow a test plan to run `build_binary_and_layer_dockerized.sh` to build a local version of the Lambda extension and then deploy it with a dummy serverless app to make sure it behaves as expected. In this PR I am adding this plan to README.md for the repo, so that other people who touch the Lambda extension know to follow the same steps.
For testing, I [inspected the new README.md here](https://github.com/DataDog/datadog-lambda-extension/blob/d706dfdc8cadc60daba84527e18a4310e4db6b00/README.md) and clicked all of the links in the Testing section to make sure they take me to the right places.

Add the test plan for the Lambda Extension to README.md

---

README.md

This PR changes references to "Lambda Extension" in the Testing section of the README to "Serverless-Init". This is because the testing described is done on Google Cloud Run, which uses the Serverless-Init binary and not the Lambda Extension.

Change README testing section to use correct verbage.

---

scripts/datadog_wrapper

Automatically enable `DD_INSTRUMENTATION_TELEMETRY_ENABLED` with AppSec so that Open-Source Software Vuln Scanning can work, which is based on telemetry data sent by the tracing libraries.
JIRA: APPSEC-11651

scripts/datadog_wrapper: appsec enables instrumentation telemetry

---

scripts/datadog_wrapper

Slightly help AppSec's onboarding by auto-enabling `DD_TRACE_ENABLED=true`. This will help in some cases where users are already leveraging the library layer and want to turn AppSec on.
APPSEC-12160

scripts/datadog_wrapper: appsec enables the apm tracing lib

---

scripts/datadog_wrapper

Introduce a simple `debug_log` helper to easily print debug logs in the datadog-wrapper script.

scripts/datadog_wrapper: introduce a debug logging helper

---

scripts/Dockerfile.build
scripts_v2/Dockerfile.build

Build extension and serverless-init with go 1.21.5. This upgrade was requested of us in an email by January 31.

Build extension with go 1.21.5.

---

build-tools/src/commands/deploy_function_command.rs

Noticed that performance tests were using the fallback Extension version: [ddserverless example](https://ddserverless.datadoghq.com/metric/explorer?start=1706304075372&end=1706908875372&paused=true#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGABuMMgYYBoAdJiqAEbJ9XAijBgi2VD1ouJOUHjanpIiwH4VENnIUzpomhoAtIragjwABM1Ym8Dy2hRQUE5wxAgdGuNOFTpXUjwgPAC6VK7ueJih4e+qnxgxUrxJ6vEAaOSLGQgeQYRYIC7KKA4GBOTJfK6ZRJoURwJxyRTKdLYqBYnFOehMZQiNweNBPfgQeyYLB4hQ5EDYkRKF48Phg+TYhAAYSkwhgKBEnzQPCAA)
We were getting 403s from Github's API because we didn't have a `User-Agent` header: https://docs.github.com/en/rest/using-the-rest-api/troubleshooting-the-rest-api?apiVersi …

Fix error on getting the latest DD Lambda Extension version

---

scripts/Dockerfile.alpine.build
scripts/Dockerfile.build
scripts/Dockerfile.race.build
scripts_v2/Dockerfile.build

Update the Go version to 1.21.7 (or just 1.21 when only the minor is needed) in some Dockerfiles.
It is blocking https://github.com/DataDog/datadog-agent/pull/22908.

Update Go version to 1.21.7

---

.gitignore
scripts/bench.sh
scripts/build_publish_deploy_bench.sh
scripts/deploy/index.js
scripts/deploy/serverless.yml
scripts/report_stats.py

Add a single script which:
- builds
- uploads the layer
- deploy a function with that layer
- invokes it N times
- computes and displays statistics over the init duration (triggering cold starts at each invoke)
It reuses existing scripts, but I had to add the steps to deploy the function, and parse logs to compute statistics, which weren't implemented in existing scripts.

[ASCII-1171] Add some scripts to automatically deploy and benchmark the extension

---

scripts/datadog_wrapper

Fixes https://github.com/DataDog/serverless-plugin-datadog/issues/477
For Java, when RemoteConfig is disabled but AppSec is enabled, it logs an error on startup. This setting should save a few CPU cycles while also suppressing the log.

feat: Set DD_APPSEC_ENABLED to false by default to avoid errors where appsec detects remoteconfig is not available

---

bottlecap/README.md
runBottlecap.sh

Supports apple m* silicon development by cross compiling to aarch64 linux and running in docker.
Still supports github codespaces:

[Bottlecap] Support Apple Silicon development

---

bottlecap/src/config.rs

`DATADOG_ROOT` is set on my machine and conflicts with this test, throwing an unexpected field error with name `root`.
This fixes it.

feat: Clear env vars before running

---

bottlecap/src/config.rs
bottlecap/src/logger.rs
bottlecap/src/main.rs
bottlecap/src/metrics/datadog.rs
bottlecap/src/metrics/dogstatsd.rs

Update configuration to be an `Arc<Config>` so we can use across services and threads.
Updated `main.rs` to reflect this changes.
Also updated the Metrics API to use the configuration instead of reading from environment variables.

feat(bottlecap): make configuration an atomic reference counter

---

bottlecap/src/main.rs

Telling in the request that we are opting for the `accountId` field.
Reconstruct function ARN.
Unblocks #217 
Logged the account ID on receipt.

feat(bottlecap): get AWS Account ID from Extension register

---

bottlecap/src/logs/agent.rs
bottlecap/src/logs/aggregator.rs
bottlecap/src/logs/datadog.rs
bottlecap/src/logs/mod.rs
bottlecap/src/logs/processor.rs
bottlecap/src/main.rs
bottlecap/src/telemetry/listener.rs

Send Telemetry API logs to Datadog.
Created the Logs Agent which handles the coordination for:
1. Logs Aggregator (needs batching mechanism).
2. Logs Processor: convert `TelemetryEvents` into `IntakeLog`s.
3. Logs API `datadog.rs`: sending data to backend.
[SVLS-4809](https://datadoghq.atlassian.net/browse/SVLS-4809)
[SVLS-4809]: https://datadoghq.atlassian.net/browse/SVLS-4809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(bottlecap): send logs to Datadog

---

bottlecap/Cargo.lock
bottlecap/Cargo.toml
bottlecap/src/config.rs
bottlecap/src/logger.rs
bottlecap/src/main.rs
bottlecap/src/metrics/datadog.rs
bottlecap/src/metrics/dogstatsd.rs

This commit removes the `SimpleLogger` entirely, using the `tracing-log` crate to route any `log` logs into the tracing subsystem. This preserves debug logs et al from `ureq` and avoids contention between two logging subsystems. I've maintained the simple formatter previously used. I've also converted every `log::` call made by our code to the use of `tracing`, further reducing confusion between the two subsystems.
`json` feature is removed from tracing, removing a dependency on `serde_json` and `tracing-serde`. Small win.

Route all logs into the tracing subsystem

---

.github/dependabot.yml
.github/workflows/rs_ci.yml
bottlecap/src/events/mod.rs
bottlecap/src/main.rs
bottlecap/src/metrics/constants.rs
bottlecap/src/metrics/dogstatsd.rs
bottlecap/src/metrics/metric.rs

This commit adds continous integration for the bottlecap sub-project, including a dependabot setup. This is patterned from the [single-machine-performance](https://github.com/DataDog/single-machine-performance) setup and includes the lessons learned over time in that repo, especially around caches.
Clippy dings are corrected, roughly, in this PR. I expect some conflicts with PR https://github.com/DataDog/datadog-lambda-extension/pull/227.

Add continuous integration for bottlecap

---

rust-toolchain.toml

This commit is a follow-on from the work done in #228. This ensures that CI and dev environments have a consistent build toolchain.

Add a rust-toolchain.toml to the project

---

bottlecap/src/logs/agent.rs
bottlecap/src/logs/aggregator.rs
bottlecap/src/logs/processor.rs
bottlecap/src/main.rs

Sets the correct `request_id` to every log.
1. The processor now has a `request_id` field which will be set on every `PlatformStart` event.
2. We set on every log the `request_id` field if available, if not, we flag it as orphan for later processing.
3. Whenever the processor get a successful `IntakeLog` from an event transformation, we flush flush orphan logs with the now available `request_id`.
Feature parity with the Go Agent.
[SVLS-4813](https://datadoghq.atlassian.net/browse/SVLS-4813)
[SVLS-4813]: https://datadoghq.atlassian.net/browse/SVLS-4813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(bottlecap): set `request_id` on every log

---

bottlecap/Cargo.toml
bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/lib.rs

This commit moves the `main.rs` down into `src/bin/bottlecap` allowing for code solely used by `bottlecap` binary to be migrated into that directory, for additional binaries to be created in the project on the same pattern and for the `bottlecap` crate to be built indepdently of its binary, useful for micro benchmarks and the like.
If it becomes desirable we can make a workspace with multiple sub-crates, in the manner of https://github.com/DataDog/single-machine-performance or https://github.com/DataDog/saluki/. I don't know that this is necessary right now.

Move `main.rs` into a binary path

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/config.rs
bottlecap/src/event_bus/bus.rs
bottlecap/src/event_bus/constants.rs
bottlecap/src/events/mod.rs
bottlecap/src/lib.rs
bottlecap/src/lifecycle/flush_control.rs
bottlecap/src/lifecycle/invocation_times.rs
bottlecap/src/logger.rs
bottlecap/src/logs/agent.rs
bottlecap/src/logs/datadog.rs
bottlecap/src/logs/processor.rs
bottlecap/src/metrics/aggregator.rs
bottlecap/src/metrics/datadog.rs
bottlecap/src/metrics/dogstatsd.rs
bottlecap/src/metrics/metric.rs
bottlecap/src/telemetry/client.rs
bottlecap/src/telemetry/events.rs
bottlecap/src/telemetry/listener.rs

This commit is a follow-on from a suggestion I had early on to make aggressive use of clippy. The changes here are mostly mechanical however some needless clones, branches have been caught and fixed. I have left some of the precision loss dings in place, note that lib.rs has a section of lints explicitly allowed. These should be an hour or two to grind out. Some of these lints are also a matter of project taste. 
Assumes that https://github.com/DataDog/datadog-lambda-extension/pull/227 will merge. Should be rebased once that PR is in `main`.

Add clippy lints to the project, address some dings 

---

bottlecap/src/logs/agent.rs
bottlecap/src/logs/aggregator.rs
bottlecap/src/logs/constants.rs
bottlecap/src/logs/datadog.rs
bottlecap/src/logs/mod.rs
bottlecap/src/logs/processor.rs

Add batching logic for the logs `aggregator.rs`.
Using Datadog's HTTP Logs API limits described in the [docs](https://docs.datadoghq.com/api/latest/logs/?code-lang=curl).
We need it, or else logs are dropped if not sent correctly.
Also [SVLS-4837](https://datadoghq.atlassian.net/browse/SVLS-4837)
- Might need to update the flushing mechanism too -> if there are multiple batches on shutdown, we need to try to flush everything on the queue.
[SVLS-4837]: https://datadoghq.atlassian.net/browse/SVLS-4837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(bottlecap): batch logs properly

---

bottlecap/Cargo.lock
bottlecap/Cargo.toml
bottlecap/src/bin/bottlecap/main.rs

I imagine that the libc allocator in a lambda environment is glibc. While it's improved over time jemalloc is often a better all-around allocator. This commit also demonstrates how one sets a global allocator for a Rust project, park it in the `main.rs` of your binary and everything linked into that binary -- except for C code, as the allocator has a prefix and doesn't overwrite `malloc` et al -- uses the allocator.

Use jemalloc as global allocator

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/lib.rs
bottlecap/src/logs/agent.rs
bottlecap/src/logs/processor.rs
bottlecap/src/metrics/aggregator.rs
bottlecap/src/tags/lambda/tags.rs
bottlecap/src/tags/provider.rs

Adds the tag provider for logs instead of simply the config tags.
This adds global tags like function ARN:

feat: Tags 4 logs

---

bottlecap/Cargo.lock
bottlecap/Cargo.toml
bottlecap/src/config.rs
bottlecap/src/config/mod.rs
bottlecap/src/config/processing_rule.rs
bottlecap/src/logs/processor.rs

Allows users to set `DD_LOGS_PROCESSING_RULES` to mask, exclude, or include, logs as desired.
An AWS Lambda with the configuration:
```
DD_LOGS=PROCESSING_RULES=[{"type": "mask_sequences", "name": "masked_value", "replace_placeholder": "masked", "pattern": "my-secret-value"},{"type": "exclude_at_match", "name": "exclude", "pattern": "exclude-me"}]
```
And the following lines in the code:
```js
console.log('this is my secret value: my-secret-value')
console.log('this log will be excluded because it matches the pattern "exclude-me"');
```
Will produce the following logs:
Where the first log was masked, and the second one was omitted.
Created a new module under `config`: `processing_rules.rs` which should use a custom deserializer set on the config.
Parity and …

feat(bottlecap): add logs processing rules

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/metrics/enhanced/lambda.rs

Increments the error metric if the runtimeDone status is not success.
Increments the timeout metric if the status is an error.

feat: Create errors metric and timeouts metric

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/metrics/aggregator.rs
bottlecap/src/metrics/enhanced/lambda.rs

- Sets duration, billed duration, max memory used, memory provisioned, and init duration metrics
- Need some calculations for post-runtime duration
- defines an aggregator test method to fetch sketches from the aggregator without compaction

feat: Set duration metrics from report log.

---

bottlecap/src/tags/lambda/tags.rs

Sets the arch tag from rust's constant. Re-maps aarch64 to arm64

set arch tag

---

bottlecap/src/logs/lambda/processor.rs
bottlecap/src/telemetry/events.rs

Adds Runtime and Post Runtime Duration to the Report Log.
Modified the Lambda Logs Processor to have an `ExecutionContext` struct to house this fields for further calculation on report event, start and end metrics set on platform start and platform runtime done, respectively.
Parity with Go and [SVLS-4861](https://datadoghq.atlassian.net/browse/SVLS-4861)
[SVLS-4861]: https://datadoghq.atlassian.net/browse/SVLS-4861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(bottlecap): add runtime and post runtime duration to logs

---

bottlecap/src/telemetry/listener.rs

Created a new `from_stream` method, which reads headers until `content-length` is found, and proceeds to read the exact remaining body size.
- Data loss and timeouts were happening due to a stream hanging waiting for data
- Stream sometimes received the data chunked, which we were never reading.
First developed in #256, also [SVLS-4932](https://datadoghq.atlassian.net/browse/SVLS-4932)
[SVLS-4932]: https://datadoghq.atlassian.net/browse/SVLS-4932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(bottlecap): fix how Telemetry API stream is being read

---

bottlecap/Cargo.lock
bottlecap/Cargo.toml
bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/logs/agent.rs
bottlecap/src/logs/aggregator.rs
bottlecap/src/logs/lambda/processor.rs
bottlecap/src/logs/processor.rs
bottlecap/src/telemetry/listener.rs

Updates how Telemetry API events are being passed through channels.
Instead of sending them to the main Event Bus, and then forwarding them to the Logs Agent. We directly send them to the Logs Agent, and there we only send the 3 events of interest back to the main Event Bus.
Another side effect is that this optimization reduces lock contention, by sending events as batches, instead of individually.
This makes it generally faster, and reduces the lock contention.
Also [SVLS-4821](https://datadoghq.atlassian.net/browse/SVLS-4821), first developed in #256 
[SVLS-4821]: https://datadoghq.atlassian.net/browse/SVLS-4821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(bottlecap): Re-architect Telemetry API events forwarding

---

scripts/Dockerfile.bottlecap.build

Cache cargo deps to compile faster. Roughly 3x improvement.
Before:
After:

feat: Cache cargo debs to compile faster

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/lifecycle/invocation_context.rs
bottlecap/src/lifecycle/mod.rs
bottlecap/src/logs/lambda/processor.rs
bottlecap/src/metrics/enhanced/constants.rs
bottlecap/src/metrics/enhanced/lambda.rs

Adds three new enhanced metrics:
- `runtime_duration`,
- `post_runtime_duration`, and
- `estimated_cost`.
[SVLS-4906](https://datadoghq.atlassian.net/browse/SVLS-4906), [SVLS-4907](https://datadoghq.atlassian.net/browse/SVLS-4907), and [SVLS-4908](https://datadoghq.atlassian.net/browse/SVLS-4908)
Added an `InvocationContext` buffer which keeps the latest 5 invocations to tracks data to calculate metrics as needed.
[SVLS-4906]: https://datadoghq.atlassian.net/browse/SVLS-4906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SVLS-4907]: https://datadoghq.atlassian.net/browse/SVLS-4907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SVLS-4908]: …

feat(bottlecap): add more enhanced metrics

---

scripts/Dockerfile.bottlecap.build

Updates the build to not consider the platform, from #269 
It doesn't build

chore(bottlecap): update where the release binary is being copied from

---

bottlecap/src/logs/lambda/processor.rs
bottlecap/src/telemetry/events.rs

Instead of using a `String`, we now accept any JSON valid value for `Function|Extension` logs
Also removed the `request_id` on `RuntimeDone` so no orphan logs get it from older invocations.
Error when setting Lambda logs to be JSON formatted, also [SVLS-4971](https://datadoghq.atlassian.net/browse/SVLS-4971)
[SVLS-4971]: https://datadoghq.atlassian.net/browse/SVLS-4971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(bottlecap): update `Function|Extension` log parsing

---

.github/workflows/serverless-vuln-scan.yml

In order to be more proactive on vulnerabilities in the serverless extension, run a vulnerability scan nightly on the agent `main` branch.
We will be able to subscribe in slack to this workflow which I will do once we're done testing it.

Move vuln scan action from agent repo.

---

.github/workflows/serverless-vuln-scan.yml

I copied this file from the agent repo. When you don't specify the repo to check out, it checks out the one in which the test is running. So, without specifying the repo, it was attempting to check out datadog-lambda-extension instead of datadog-agent.

Specify repo to check out in vulnerability scan.

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/metrics/aggregator.rs
bottlecap/src/metrics/constants.rs
bottlecap/src/metrics/datadog.rs
bottlecap/src/metrics/enhanced/lambda.rs
bottlecap/src/metrics/flusher.rs

- create methods for serializing the payload within byte size/entry size limits. Not sure if the entry size limit makes sense though
From the docs of `api/v2/series` there is only a byte restriction https://docs.datadoghq.com/api/latest/metrics/#submit-metrics. For the `api/beta/sketches` there is no public docs available I think
- flusher loops over them until everything that can be send, is sent. The skipped metrics/sketches will still pollute the buffer though
- flusher should not lock for all that time. A good solution to avoid excess mutex usage could be to copy the outgoing buffer

Svls 4840 metrics api limit

---

bottlecap/src/telemetry/client.rs

Add `extension` as part of the events to subscribe to from the [Telemetry API](https://docs.aws.amazon.com/lambda/latest/dg/telemetry-api.html#telemetry-api-subscription).
We were not subscribing because I was avoiding spamming our logs.

chore(bottlecap): subscribe to `extension` telemetry events

---

bottlecap/src/config/mod.rs

This fails over to the main agent if appsec is enabled.
The reason is that the CDK construct adds this env var by default.

feat: Allow appsec but in a disabled-only state until we add support for the runtime proxy

---

bottlecap/src/logs/lambda/processor.rs

Small goof on a refactor caused us to push the successfully processed log when handling orphans after we get a request ID.
This meant orphan logs weren't sent, and that we doubled up on successful logs.

fix: Don't send duplicate logs during orphan processing

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/traces/stats_flusher.rs
bottlecap/src/traces/trace_processor.rs

My mistake, I thought the API key would be updated on the config.
Instead we just need to pass the resolved key.

fix: Use resolved API key

---

local_tests/golang/go.mod
scripts/Dockerfile.alpine.build
scripts/Dockerfile.build
scripts/Dockerfile.race.build
scripts_v2/Dockerfile.build

The agent now uses Go `1.22.5`, this repo should also use `1.22.x`.

Update Go version to 1.22.5

---

bottlecap/src/tags/lambda/tags.rs

For backwards compatibility reasons we need to use the lowercase ARN in the tags.

fix: use lowercase ARN

---

bottlecap/src/traces/hello_agent.rs

Warns users that this is a deprecated route and they should upgrade the tracing library.

feat: warn on hello

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/logs/agent.rs
bottlecap/src/logs/lambda/processor.rs
bottlecap/src/logs/processor.rs
bottlecap/src/telemetry/listener.rs

Use `hyper` crate instead of parsing payload for the telemetry API.
We should have done this since the start, but we weren't using tokio

chore(bottlecap): add `hyper@0.x` in telemetry api

---

README.md

Fix the broken link for contributing procedures.

Fix dead link for contributing.md

---

bottlecap/src/config/mod.rs

Failovers to Go binary when `datadog.yaml` is present.
`figment` crate doesn't match properly fields from `YAML` and environment variables. Therefore, if users had some configuration values enabled, we might not be able to honor them properly, due to how they're processed by figment.
This should be reverted once configuration is done accordingly for environment variables and `YAML`

chore(bottlecap): fallback on `datadog.yaml` usage

---

bottlecap/src/metrics/aggregator.rs
bottlecap/src/tags/lambda/tags.rs
bottlecap/tests/logs_integration_test.rs

Adds `dd_extension_version` to the tags.
We need it.
Also [SVLS-5154](https://datadoghq.atlassian.net/browse/SVLS-5154)
Currently, we are setting a hardcoded value `61-next` which should indicate the current version of the package. This needs to be updated to not be hardcoded. Keeping it only for closed beta.
[SVLS-5154]: https://datadoghq.atlassian.net/browse/SVLS-5154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(bottlecap): add `dd_extension_version` to tags

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/config/mod.rs

When loading Rust, a `println` explicitly marked an `Error` which would end up in customers Lambdas, this might appear as confusing, since we end up going into failover with Go
We should have removed this, but we forgot that this could appear on every customer 🤦🏽.
Also `#incident-29136`

fix(bottlecap): remove log that might confuse customers

---

.gitlab/scripts/build_bottlecap.sh
.gitlab/scripts/build_go_agent.sh
.gitlab/scripts/build_image.sh
.gitlab/templates/lambda-extension.yaml.tpl
scripts/Dockerfile
scripts/Dockerfile.alpine
scripts/Dockerfile.bottlecap.alpine.build

The container images published for `v61` had a mismatch in agent resolution. Our monitors didn't notify us 🤦🏽.
This solved the uncaught typo mismatch and also adds an alpine build for Bottlecap.
#331 and `#incident-29136`
Manual tested:
- `arm64` and `amd64` image, and
- `arm64` and `amd64` image for alpine.

fix: image builder agent resolution

---

.gitlab-ci.yml
.gitlab/scripts/build_go_agent.sh

Tags builds with latest agent, setting the default to the current latest.
We were not tagging the build with the proper Agent version, fallbacking to `6.0`, which is incorrect.

fix: require `AGENT_VERSION` to tag the build properly

---

bottlecap/src/config/mod.rs

Adds a couple environment variables to be ignored, since they're being used by the Datadog Lambda Library layers.
- `DD_COLD_START_TRACING`
- `DD_MIN_COLD_START_DURATION`
- `DD_COLD_START_TRACE_SKIP_LIB`

chore(bottlecap): add cold start environment variables

---

bottlecap/src/bin/bottlecap/main.rs

Bias the main loop, deprioritize the `flush_interval.tick()` check in favor of the event bus.

feat: bias main select

---

.gitlab/Dockerfile
scripts/Dockerfile.bottlecap.alpine.build
scripts/Dockerfile.bottlecap.build

Move to `stable` toolchain for rust.
Arm64 Alpine build is failing due to `rustc` being updated on `nightly` toolchain.
Not updating the `.dev` Dockerfile

fix(bottlecap): remove `nightly` in favor or `stable`

---

bottlecap/src/bin/bottlecap/main.rs

Followup from #331 for local emulators.
There's no telemetry API so we can't process logs or handle the lifecycle, so we'll just idle and call `next` infinitely.
Because of the missing API keys and lack of secrets, this drops us into the `can't decrypt secrets` catch-all. We may consider creating one specifically for local emulation, but my guess is the key would be switching over when we detect there is no telemetry API.

feat: Remove excepts from secrets, drop into idle loop when local

---

bottlecap/src/config/mod.rs

Allows a few more ENV vars which we don't use or modify at the agent level, so they are safe to use with bottlecap

feat: Open up more env vars which we don't rely on

---

bottlecap/src/config/mod.rs

Allows `DD_TRACE_DISABLED_PLUGINS` for people who want to optionally disable some plugins in the tracer.

feat: Allow trace disabled plugins

---

scripts/Dockerfile.bottlecap.dev

We use stable for alpine and the other builds, I think this is a holdover.
As bottlecap leaves beta and approaches stable, we can explore using nightly to remove the crash handler.

feat: Use stable instead of nightly

---

bottlecap/src/config/mod.rs

Allowing more env vars which we either don't use in serverless or aren't used by the lambda extension
except profiling, which we will fail over into the main agent if it's present and enabled

feat: Allowlist additional env vars

---

bottlecap/src/logs/aggregator.rs
bottlecap/src/logs/flusher.rs
bottlecap/src/logs/lambda/processor.rs

Reduces allocations for logs components
- Aggregator
- Processor
Just save some allocations by pre-allocating vectors and not generating them everytime.

chore(bottlecap): reduce allocations for logs processing

---

.github/workflows/release-serverless-init.yml

We should be tagging each release in the datadog-agent repo. This way, when we do a release we can pin the release to a specific datadog-agent tag instead of going off of main.

[serverless-init] Use branches or tags when releasing serverless-init

---

bottlecap/src/config/mod.rs

Moves the `Failover` specific configuration to its own struct, allowing us to failover fast.
It's easier to maintain having this deny list, by quickly checking the values of `extension_version` from Env and Yaml before checking other values expected.
Also updated how we merge logs processing rules, as Env has precedence over Yaml

chore(bottlecap): fast failover

---

bottlecap/src/config/mod.rs

Stops failing over when the `AWS_LAMBDA_EXEC_WRAPPER` is set to the `/opt/datadog_wrapper`
We need it for Universal Instrumentation, #374

fix(universal-instrumentation): accept `datadog_wrapper`

---

bottlecap/src/metrics/constants.rs
bottlecap/src/traces/trace_agent.rs

I tested this out with 10k contexts along with Python APM tracing enabled and we barely touched 74mb, so I think 10x-ing this is fine and unblocks our customer for now.
We can replace this with a bump allocator or dynamic flushing as needed, but I think this is the fastest path to resolution

feat: increase to 10k contexts

---

bottlecap/Cargo.lock
bottlecap/Cargo.toml
bottlecap/src/bin/bottlecap/main.rs

Required now for as rustls will be upset if both `ring` and `aws-lc-rs` are present.

feat: Specify aws_lc_rs as our default crypto provider

---

bottlecap/Cargo.lock
bottlecap/Cargo.toml

1. We merged dogstatsd upstream to libdatadog, but we left all the dependencies in main. This removes those dependencies
2. By default cargo will use the patch version of whatever we install, and now we're a few fixes behind. I'm switching everything to grab the latest patch release for every minor version and will give a second pass for things we can open up to any major.
3. Updates licenses

feat: Remove unused deps, drop minor version pins and update

---

.gitlab/scripts/check_layer_size.sh

I missed this in the last PR, should have bumped both

feat: Bump unzipped size too

---

scripts/Dockerfile.build
scripts_v2/Dockerfile.build

Nightly vulnerability scan began failing over the weekend. This should fix the failures.
https://github.com/DataDog/datadog-lambda-extension/actions/runs/10755426699/job/29893196072

Bump go version used for building extension.

---

bottlecap/src/config/mod.rs

I combined the two possibilities into one log, which is fine because we know both exist and we've got the right fix in flight.

feat: failover on dd proxy

---

bottlecap/src/traces/trace_agent.rs
bottlecap/src/traces/trace_processor.rs

Decouples `hyper` from the Trace processor.
The trace processor should be abstracted from any http/https client. As it's job is to process traces, not hyper requests.
This pre processing for the request should be done at the agent level.
- Updated unit tests
- Tested manually for JS
To be upstream to libdatadog

chore: decouple `hyper` from `trace_processor`

---

bottlecap/src/tags/lambda/tags.rs

check the DD_RUNTIME env var and use it as runtime
No fallback to proc logic or default value is used to avoid the worst case scenario:
- Datadog integration picks up the AWS runtime, and set it
- lambda function with no `DD_RUNTIME` set will scan proc. It's still not populated, so the `provided.al2023` will be read
- `DD_RUNTIME` is then set with a different value from the one from AWS
- each datapoint will have either AWS runtime+`provided.al2023` or AWS runtime+`DD_RUNTIME`
in the best case scenario, `DD_RUNTIME` is set with the same value of the AWS runtime, or the AWS integration is disabled.
In both case, it seems that the proc scan fallback will add a value not useful and confusing, so it might be better to remove it altogether

feat: use dd_runtime tag

---

.gitlab/datasources/regions.yaml

Adds `ap-southeast-5` region to our datasources
Updated `datasources/regions.yaml`

fix: add `ap-southeast-5` region

---

.github/workflows/retry-workflow.yml
.github/workflows/serverless-vuln-scan.yml

Our vulnerability scanner seems to fail pretty often for infrastructure related reasons. When retried, they pass just fine. 
This PR aims to add auto-retries to the vuln scan action.
Note that I am unable to test the retry logic end to end. I created a new github action which cannot be triggered until it hits main.
The plan is to merge this PR, then test a forced failure and ensure it is retried.

Retry vulnerability scanner on failure.

---

.github/workflows/serverless-vuln-scan.yml

Seeing error when running nightly [vulnerability scan](https://github.com/DataDog/datadog-lambda-extension/actions/runs/11421773466/job/31779610353)
```
Running Trivy with options: trivy image public.ecr.aws/datadog/lambda-extension:latest
2024-10-20T01:32:03Z	INFO	[vulndb] Need to update DB
2024-10-20T01:32:03Z	INFO	[vulndb] Downloading vulnerability DB...
2024-10-20T01:32:03Z	INFO	[vulndb] Downloading artifact...	repo="ghcr.io/aquasecurity/trivy-db:2"
2024-10-20T01:32:04Z	ERROR	[vulndb] Failed to download artifact	repo="ghcr.io/aquasecurity/trivy-db:2" err="OCI repository error: 1 error occurred:\n\t* GET https://ghcr.io/v2/aquasecurity/trivy-db/manifests/2: TOOMANYREQUESTS: retry-after: 1.084625ms, allowed: 44000/minute\n\n"
2024-10-20T01:32:04Z	FATAL	Fatal error	init error: DB error: …
```

Instruct trivy to use fallback for downloading db.

---

bottlecap/src/config/mod.rs
bottlecap/src/config/trace_propagation_style.rs
bottlecap/src/traces/context.rs
bottlecap/src/traces/propagation/mod.rs
bottlecap/src/traces/propagation/text_map_propagator.rs

Creates a composite propagator to extract trace context.
This is because we have specific logic on how we handle/resolve trace context in the tracers.
- New struct `DatadogCompositePropagator` using `DatadogHeaderPropagator` and `TraceContextPropagator`.
- Added configuration options so the propagator can decide how to act.
[SVLS-5769](https://datadoghq.atlassian.net/browse/SVLS-5769) and...
- Maintain feature parity with the tracers.
- Unit tests were copied from Python tracer, seen as the source of "true".
[SVLS-5769]: https://datadoghq.atlassian.net/browse/SVLS-5769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(bottlecap): Add Composite Trace Propagator

---

.gitlab/scripts/check_layer_size.sh
scripts/Dockerfile.alpine.build
scripts/Dockerfile.build

Lambda functions created from container image [install the Datadog Lambda Extension](https://docs.datadoghq.com/serverless/aws_lambda/installation/go/?tab=containerimage) from the [Amazon ECR repository](https://gallery.ecr.aws/datadog/lambda-extension). 
We maintain two separate build configurations:
- Regular build (`Dockerfile.build`)
- Alpine-specific build (`Dockerfile.alpine.build`)
The regular build script correctly updates the agent version when `$AGENT_VERSION` env var is set. The Alpine build script is missing this version update logic, causing it to display an incorrect version (6.0.0).
https://github.com/DataDog/datadog-lambda-extension/blob/f7482ce3fbced54bcddd22aa5f5175fbac0fcc9d/scripts/Dockerfile.build#L33-L44
https://github.com/DataDog/datadog-lambda-extension/blob/7ea21c6 …

Display correct Agent version in Alpine builds

---

.github/workflows/serverless-vuln-scan.yml

Customer reported vulnerabillites discovered in latest released version of serverless-init.
Adds vulnerability scanning of serverless-init with both trivy and grype to the nightly vulnerability scan action.
I also rearranged the action steps. Building the serverless binary is very slow, so it is now done last.
If you're struggling to review, go commit by commit.

Add testing of serverless-init latest to vuln scanner.

---

.github/workflows/serverless-vuln-scan.yml
scripts/Dockerfile.alpine.build

Bumps go version in alpine image to 1.23.2.
Address vulnerabilities CVE-2024-34156 & CVE-2024-34158.
Related to https://github.com/DataDog/datadog-lambda-extension/pull/425
Build serverless-init locally and run `trivy image <image name>` to confirm vulnerabilities are addressed.

Bump go version in alpine image to 1.23.2

---

bottlecap/src/lifecycle/invocation/span_inferrer.rs
bottlecap/src/tags/lambda/tags.rs

Generate a secure random id on snap start Lambdas
It's needed, @DylanLovesCoffee made a research about this a couple years ago.
- Tested in Java

fix(bottlecap): secure random id on snap start lambdas

---

scripts/Dockerfile.alpine.build

**What this does:**
This change builds the go-agent as a statically linked library when building for alpine. 
**Why make this change:**
A customer experience an issue using the extension in a container image that was using a really outdated version of GLIBc (2.17) for their go application. Where as our typical binary is compiled against GLIBc version (2.18). This was a current aws provided image so we could not advise the customer to update their base image. An easier solution would offer a statically linked library using a lightweight c library such as the one from alpine (musc). This will ensure compatibility across multiple linux environments. 
**Testing**  
I tested the new build with a container image that matched the environment the customer had. Previously the customer would …

Adding static flag to build parameters for alpine images

---

bottlecap/src/lifecycle/invocation/context.rs
bottlecap/src/lifecycle/invocation/triggers/mod.rs
bottlecap/src/metrics/enhanced/lambda.rs
bottlecap/src/proc/mod.rs
bottlecap/src/traces/mod.rs
bottlecap/src/traces/propagation/mod.rs
bottlecap/src/traces/propagation/text_map_propagator.rs
bottlecap/src/traces/trace_processor.rs

Filters spans through a more strict set of rules
We need to filter out spans generated by us, or created by other internal systems

fix(bottlecap): filter http, tcp and local spans

---

bottlecap/src/lifecycle/invocation/processor.rs
bottlecap/src/lifecycle/invocation/span_inferrer.rs
bottlecap/src/lifecycle/invocation/triggers/dynamodb_event.rs
bottlecap/src/lifecycle/invocation/triggers/mod.rs
bottlecap/tests/payloads/dynamodb_event.json

Adds support for DynamoDB inferred spans
Added `DynamoDbEvent` to serialize it

feat(bottlecap): add DynamoDB inferred spans

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/lifecycle/invocation/processor.rs

Moves where enhanced metrics are being called to be aggregated.
Reduce the footprint in `main.rs`, and to have more control over the whole invocation lifecycle.
Also unblocks #444

chore(bottlecap): move `EnhancedMetrics` to live in `InvocationProcessor`

---

bottlecap/src/lifecycle/invocation/mod.rs
bottlecap/src/lifecycle/invocation/processor.rs
bottlecap/src/lifecycle/invocation/span_inferrer.rs
bottlecap/src/lifecycle/invocation/triggers/mod.rs
bottlecap/src/lifecycle/invocation/triggers/sns_event.rs
bottlecap/src/lifecycle/listener.rs

Uses the error data sent by traces to attach it to the invocation span.
Using the headers data sent by the tracers on end invocation, also sends a metric.
- We might need to go back to this code to see how it behaves for Timeouts
- Metrics look off in the screenshot, but rest assured they're good, it's (1+4) invocations and (5) errors

feat(bottlecap): set error to invocation span

---

bottlecap/src/lifecycle/invocation/span_inferrer.rs
bottlecap/src/lifecycle/invocation/triggers/dynamodb_event.rs
bottlecap/src/lifecycle/invocation/triggers/event_bridge_event.rs
bottlecap/src/lifecycle/invocation/triggers/sqs_event.rs
bottlecap/tests/payloads/eventbridge_sqs_event.json

feat(bottlecap): add EventBridge-SQS inferred spans

---

bottlecap/src/lifecycle/invocation/span_inferrer.rs
bottlecap/src/lifecycle/invocation/triggers/dynamodb_event.rs
bottlecap/src/lifecycle/invocation/triggers/event_bridge_event.rs
bottlecap/src/lifecycle/invocation/triggers/kinesis_event.rs
bottlecap/src/lifecycle/invocation/triggers/mod.rs
bottlecap/tests/payloads/kinesis_event.json

feat(bottlecap): add Kinesis inferred spans

---

bottlecap/Cargo.toml
bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/lifecycle/invocation/context.rs
bottlecap/src/lifecycle/invocation/processor.rs
bottlecap/src/metrics/enhanced/constants.rs
bottlecap/src/metrics/enhanced/lambda.rs
bottlecap/src/metrics/enhanced/mod.rs
bottlecap/src/metrics/enhanced/statfs.rs

This PR introduces three new enhanced lambda metrics. These metrics are emitted once per invocation and represent space used and space available in the `/tmp` directory.
The three new metrics are:
- `aws.lambda.enhanced.tmp_max` - max available bytes in `/tmp`
- `aws.lambda.enhanced.tmp_used` - bytes used or reserved in `/tmp`
- `aws.lambda.enhanced.tmp_free` - bytes available in `/tmp`
- Build the lambda extension
- Create a lambda function with the extension built in previous step
- Turn on lambda insights / add the [lambda insights extension](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-Getting-Started.html) to your function
- Invoke the function
- View the new enhanced metrics in metrics explorer or [this …

feat(bottlecap): generate tmp enhanced metrics

---

bottlecap/src/lifecycle/invocation/span_inferrer.rs
bottlecap/src/lifecycle/invocation/triggers/dynamodb_event.rs
bottlecap/src/lifecycle/invocation/triggers/event_bridge_event.rs
bottlecap/src/lifecycle/invocation/triggers/sns_event.rs
bottlecap/tests/payloads/eventbridge_sns_event.json

feat(bottlecap): add EventBridge-SNS inferred spans

---

bottlecap/src/lifecycle/invocation/span_inferrer.rs
bottlecap/src/lifecycle/invocation/triggers/api_gateway_http_event.rs
bottlecap/src/lifecycle/invocation/triggers/lambda_function_url_event.rs
bottlecap/src/lifecycle/invocation/triggers/mod.rs
bottlecap/tests/payloads/lambda_function_url_event.json

Adds Lambda Function Url inferred spans
Adding the `LambdaFunctionUrlEvent` trigger implementation

feat(bottlecap): add Lambda Function URL inferred spans

---

bottlecap/src/config/mod.rs
bottlecap/src/lifecycle/invocation/mod.rs
bottlecap/src/lifecycle/invocation/processor.rs
bottlecap/src/lifecycle/listener.rs

Allow customers to capture the lambda payload for request and response
Created a function which converts a `serde_json::Value` into span meta tags.

feat(bottlecap): add capture lambda payload

---

bottlecap/src/metrics/enhanced/lambda.rs

Missed to add dynamic value tags to new enhanced metrics

fix(bottlecap): add missing tags to enhanced metrics

---

.gitlab/scripts/check_layer_size.sh

Increase the threshold again, can't run a release

chore(gitlab): increase threshold for check-layer-size job

---

bottlecap/src/lifecycle/invocation/context.rs
bottlecap/src/lifecycle/invocation/span_inferrer.rs
bottlecap/src/lifecycle/invocation/triggers/lambda_function_url_event.rs
bottlecap/src/lifecycle/invocation/triggers/s3_event.rs
bottlecap/src/lifecycle/invocation/triggers/sns_event.rs
bottlecap/src/lifecycle/invocation/triggers/sqs_event.rs
bottlecap/src/lifecycle/invocation/triggers/step_function_event.rs
bottlecap/src/metrics/enhanced/lambda.rs
bottlecap/src/proc/mod.rs
bottlecap/src/traces/propagation/mod.rs
bottlecap/src/traces/propagation/text_map_propagator.rs
bottlecap/tests/payloads/eventbridge_sqs_java_header_event.json

feat(bottlecap): add aws trace header for java and sqs

---

bottlecap/src/metrics/enhanced/lambda.rs

Temporarily disables `tmp`, `fd`, and `threads` metrics.
To explore other less-performance impacting implementations.

chore(bottlecap): temporarily disable extra metrics

---

bottlecap/src/lifecycle/invocation/processor.rs
bottlecap/src/metrics/enhanced/lambda.rs
bottlecap/src/proc/constants.rs
bottlecap/src/tags/lambda/tags.rs

Adds the `runtime` tag to the invocation span and metric tags.

feat(bottlecap): add `runtime` tag

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/lifecycle/invocation/processor.rs

Handles timeouts properly by sending tracing data as expected

feat(bottlecap): handle timeouts

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/events/mod.rs
bottlecap/src/lifecycle/invocation/processor.rs
bottlecap/src/logs/lambda/processor.rs
bottlecap/src/metrics/enhanced/lambda.rs

Handles OOM exceptions, sending enhanced metric as expected.
Metrics look iffy, but that's OK, because when the sandbox get's signal-killed, there's no way for us to tell that we got OOM as of now.

feat(bottlecap): handle OOM exceptions

---

bottlecap/src/traces/trace_processor.rs

When `DD_SERVICE` is set, `aws.lambda` spans service should be that, this can happen in NodeJS

fix(bottlecap): fix `aws.lambda` service naming

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/secrets/decrypt.rs

Tries decrypting the KMS API Key without passing any context, as we do this in the Go Extension

fix(bottlecap): try kms decrypt without context as in goagent

---

bottlecap/src/config/mod.rs

Customers will now default to use the Rust extension – although we fallback to Go in certain scenarios, we have a explicit value in order for them to force the launch of the Go extension.
Flipping the values to be `legacy` instead of `next`.
So no opt-in, but opt-out.

feat(bottlecap): fallback on opted out only

---

bottlecap/src/config/mod.rs

fix(bottlecap): fallback on yaml otel config

---

bottlecap/src/config/mod.rs
bottlecap/src/logs/lambda/processor.rs

1. Looks like we had this at some point and either removed it or it was not completed (my bad ya'll!)
2. Honors `DD_SERVERLESS_LOGS`
3. Sets it as default: true. This is a breaking change from the main agent which defaults to false, but every single integration (cdk construct, serverless plugin, macro) enables it by default with opt-in (so if the customer actively disables it, the env var is still set), so I think this is safe.
fixes https://github.com/DataDog/datadog-lambda-extension/issues/476

feat: honor serverless_logs

---

scripts/Dockerfile.build
scripts_v2/Dockerfile.build

Updates Go version to `1.23.2`
Go version was updated for alpine in #426 but not for all other places

chore: update Go version in multiple places

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/secrets/decrypt.rs

Current logic was ignoring kms/secret arn when dd_api was set, but from the docs and goagent behavior it should be the other way around 
https://docs.datadoghq.com/serverless/libraries_integrations/cli/
> Datadog API Key encrypted using KMS. Sets the DD_KMS_API_KEY environment variable on your Lambda function configuration. Note: DD_API_KEY is ignored when DD_KMS_API_KEY is set.
> 	The ARN of the secret storing the Datadog API key in AWS Secrets Manager. Sets the DD_API_KEY_SECRET_ARN on your Lambda function configuration. Notes: DD_API_KEY_SECRET_ARN is ignored when DD_KMS_API_KEY is set. Add the secretsmanager:GetSecretValue permission to the Lambda execution role.
Also remove the 32 char hex validation

priority of decrypt: kms > arn > use dd_api_key

---

bottlecap/src/tags/lambda/tags.rs

chore: upgrade version to `v67`

---

bottlecap/src/config/mod.rs
bottlecap/src/http_client.rs

The main agent limits this to [5 seconds fixed](https://github.com/DataDog/datadog-agent/blob/924a1502fdb70f35064838fa1bbf27b54459fb1b/pkg/serverless/daemon/daemon.go#L34), I wanted to make it configurable.

feat: Flush timeouts

---

bottlecap/Cargo.lock
bottlecap/Cargo.toml
bottlecap/LICENSE-3rdparty.yml

Lambda library sends the invocation metric, we send it from here too.
Just ignore it so we don't duplicate it.

fix(bottlecap): dogstatsd to filter invocations from lambda library

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/lifecycle/flush_control.rs
bottlecap/src/lifecycle/invocation_times.rs
bottlecap/src/lifecycle/mod.rs

I removed this initially as I believed it either wasn't necessary or didn't help much (I think? I had just had a baby)
We've since gotten some feedback that, although users can set `DD_SERVERLESS_FLUSH_STRATEGY=periodically,10000` to flush every 10s regardless of the number of invocations, they prefer the automatic adaptive strategy we had earlier.
So I'm adding this back

Feat: support adaptive flush strategy again

---

bottlecap/src/lifecycle/flush_control.rs

Customer feedback from high volume functions shows this tick rate is simply too frequent. Customers can always change this with the `DD_SERVERLESS_FLUSH_STRATEGY` option.

feat: Set default flush interval to 30s

---

bottlecap/src/lifecycle/flush_control.rs

1min default is in line with the datadog-agent. To avoid a breaking change, we'll keep it at 1min here.

feat: 1min default

---

bottlecap/src/config/mod.rs

Prevents a bug where data is being set to the wrong intake, by fallbacking to the main agent while we support the feature in Rust.
Adding a fallback check when the configuration settings are present for `DD_URL`, APM, and Logs intake urls
Configured intake URLs are not supported yet for the Rust extension
#493

fix: fallback on intake urls

---

bottlecap/src/lifecycle/invocation/processor.rs

Decodes error.msg and error.type headers as was previously done for the error.stack header, because of https://github.com/DataDog/dd-trace-dotnet/pull/6438 encoding error.msg and error.type.
[\[SLES-2001\] .NET Datadog Tracer throws exception from AWS Lambda Function](https://datadoghq.atlassian.net/browse/SLES-2001)
[\[SVLS-6041\] Having non-ascii characters in a stack trace causes an exception within the tracer.](https://datadoghq.atlassian.net/browse/SVLS-6041)
Tested with a lambda that throws an exception with an error message containing a non-ASCII character.
[SLES-2001]: https://datadoghq.atlassian.net/browse/SLES-2001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SVLS-6041]: https://datadoghq.atlassian.net/browse/SVLS-6041?atlOrigin=ey …

Decode error message and error type

---

bottlecap/src/lifecycle/invocation/triggers/api_gateway_http_event.rs
bottlecap/src/lifecycle/invocation/triggers/api_gateway_rest_event.rs
bottlecap/src/lifecycle/invocation/triggers/lambda_function_url_event.rs
bottlecap/src/lifecycle/invocation/triggers/mod.rs
bottlecap/tests/payloads/api_gateway_http_event.json

Converts a serializer into a deserializer
I confused `serializer` with `deserializer`, so header keys were never lowercased, causing issues in trace propagation, because the propagator expects `x-datadog-trace-id`, but in some tracers, this data is sent as `X-Datadog-Trace-Id`, like the Ruby tracer.

fix: turn headers serializer into a deserializer

---

bottlecap/LICENSE-3rdparty.yml
bottlecap/src/metrics/enhanced/constants.rs
bottlecap/src/metrics/enhanced/lambda.rs

Based on self-monitoring tests, this should fix the issue of the process-based metrics adding a lot of post-runtime duration overhead.
[Full investigation doc](https://docs.google.com/document/d/1nn-dcJwxtvH6Fs_Dnj_QNm9c_KrSvWCv4s0TyJ7E4k8/edit?usp=sharing)

Enable tmp, fd, and threads enhanced metrics

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/config/mod.rs
bottlecap/src/lifecycle/invocation/triggers/api_gateway_http_event.rs
bottlecap/src/lifecycle/invocation/triggers/api_gateway_rest_event.rs
bottlecap/src/lifecycle/invocation/triggers/mod.rs
bottlecap/src/lifecycle/invocation/triggers/sqs_event.rs
bottlecap/src/secrets/decrypt.rs

Addressing bug report https://github.com/DataDog/datadog-lambda-extension/issues/508
As per AWS doc https://aws.amazon.com/blogs/enterprise-strategy/getting-started-with-aws-services-in-aws-china-beijing-region-and-aws-china-ningxia-region/ the AWS regions in China have different domain and arn
>- AWS China Regions names are as follows. Beijing: cn-north-1; Ningxia: cn-northwest-1.
>- In AWS China Regions, the Amazon Resource Name (ARN) syntax includes a cn. For example: arn:aws-cn:iam::123456789012:user/division_abc/subdivision_xyz/Bob.
the domain in ARN for the services should be `amazonaws.com.cn` as per doc
https://docs.amazonaws.cn/en_us/aws/latest/userguide/endpoints-Beijing.html
https://docs.amazonaws.cn/en_us/aws/latest/userguide/endpoints-Ningxia.html

fix: set right domain and arn by region on secrets manager

---

bottlecap/src/tags/lambda/tags.rs
bottlecap/src/tags/provider.rs
bottlecap/src/traces/trace_processor.rs

Adds all global tags to the top level trace tags hash map.
Working in conjunction with the apm-trace-intake team, intake will ensure that these tags are placed onto all spans in the trace and then are made available for our usage metric.
Part of the [usage metrics tagging](https://docs.google.com/document/d/18MYBXj2ugcaWlLUms8J0qBXN57Ct354YJM5y09XSUhw/edit?tab=t.0#heading=h.hn9uiefsp3ng) which will allow us to include more tags (including custom tags) on the `datadog.serverless.traced_invocations` metric.
Note that this change will duplicate the location of the global tags in the trace payload sent to intake. Currently, these payloads look like
```
TracePayload {
...
Chunk {
...
Span {
...
Meta {
...
"key1": "value1",
"key2": "value2",
"key3": "value3"
}
}
}
Tags {}
}
```
After this …

Add _dd.tags.function to top level trace tags hashmap.

---

bottlecap/src/traces/trace_agent.rs

- Updates the trace success response to report a 200 Ok status code instead of 202 Accepted status code
- Returns a `"rate_by_service"` map to satisfy this requirement by the tracer.
[Excessive warn logs reported by customer](https://github.com/DataDog/datadog-lambda-extension/issues/510)
The Java Tracer was sending warn logs because it expects a response status code of 200 on success:
```
{"message":"Successfully buffered traces to be flushed."} while sending 1 (size=2KB) traces. Total: 22, Received: 22, Sent: 0, Failed: 22. Status: 202 Accepted (Will not log warnings for 5 minutes)
```
After updating the status code, the Java tracer was sending an error since the success response body contains a `message` attribute instead of `rate_by_service`:
```
[dd.trace 2025-01-17 22:48:37:287 …
```

fix: traces success response to be Ok instead of Accepted

---

bottlecap/src/config/mod.rs

Fixes #514 by checking if NO_PROXY contains DD_SITE domain, and the the user is likely relying on privatelink endpoints + private DNS isntead of an HTTP proxy for telemetry data.
This is kind of a hack in 2 ways:
1. `reqwest` has some support for NO_PROXY but `hyper-proxy` doesn't. I could use the built in version, but either way I'd need to build it myself
2. We simply pass a proxy string to libdatadog for APM + statsd, we don't actually pass config anywhere. So we'd have to add that.
This solution works for the customer reporting it, as their NO_PROXY string includes `datadoghq.com`.
But I wonder if there's a use case for a customer who would use privatelink for, say metrics only - but then use an HTTP proxy for logs (perhaps to inspect logs for PII or some other form of compliance).
In …

fix: Honor noproxy and skip proxying if ddsite is in the noproxy list

---

.github/workflows/codeql-analysis.yml
.github/workflows/redirect_issues.yml
.github/workflows/release-serverless-init.yml
.github/workflows/retry-workflow.yml
.github/workflows/rs_ci.yml
.github/workflows/serverless-vuln-scan.yml
scripts/Dockerfile.alpine.build
scripts/Dockerfile.bottlecap.alpine.build
scripts/Dockerfile.bottlecap.build
scripts/Dockerfile.bottlecap.dev
scripts/Dockerfile.build
scripts/Dockerfile.race.build
scripts_v2/Dockerfile.build

Pins the Ubuntu version for Serverless-init release to `22.04`.
Serverless Integration tests failing with the below error.
```
gcc: internal compiler error: Segmentation fault (program cc1)
```
Confirmed that Serverless Integration tests passed successfully.
Tests started failing on this image version:
```
Runner Image
Image: ubuntu-24.04
Version: 20250120.5.0
```
Tests were previously passing on this image version:
```
Runner Image
Image: ubuntu-24.04
Version: 20250105.1.0
```

Update/pin ubuntu from latest to 24.04

---

.github/workflows/codeql-analysis.yml
.github/workflows/redirect_issues.yml
.github/workflows/release-serverless-init.yml
.github/workflows/retry-workflow.yml
.github/workflows/rs_ci.yml
.github/workflows/serverless-vuln-scan.yml
scripts/Dockerfile.alpine.build
scripts/Dockerfile.bottlecap.alpine.build
scripts/Dockerfile.bottlecap.build
scripts/Dockerfile.bottlecap.dev
scripts/Dockerfile.build
scripts/Dockerfile.race.build
scripts_v2/Dockerfile.build

Pins the Ubuntu version for Serverless-init release to `22.04`.
Serverless Integration tests failing with the below error.
```
gcc: internal compiler error: Segmentation fault (program cc1)
```
Confirmed that Serverless Integration tests passed successfully.
Tests started failing on this image version:
```
Runner Image
Image: ubuntu-24.04
Version: 20250120.5.0
```
Tests were previously passing on this image version:
```
Runner Image
Image: ubuntu-24.04
Version: 20250105.1.0
```

update ubuntu from latest to pinned 22.04 

---

.github/workflows/release-serverless-init.yml

Adds write permissions for packages and content for release-serverless-init.yml 
Based on [VULN-8322](https://datadoghq.atlassian.net/browse/VULN-8322?atlOrigin=eyJpIjoiMTBiNzNmZjRkM2VjNDdmMWFkODFhYzNiMWQyYjM0MDQiLCJwIjoiaiJ9) repo update
[VULN-8322]: https://datadoghq.atlassian.net/browse/VULN-8322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
tested [here](https://github.com/DataDog/datadog-lambda-extension/actions/runs/12992195548) successfully

Elevate permissions to write packages for release-serverless-init.yml

---

.github/workflows/rs_ci.yml
bottlecap/LICENSE-3rdparty.yml

Updates the 3rdparty license files

fix: licenses

---

bottlecap/tests/metrics_integration_test.rs

Apple silicon still has a failure which made me think this test was broken but it wasn't

Re add as I got the failure wrong

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/config/mod.rs
bottlecap/src/lifecycle/invocation/processor.rs
bottlecap/src/secrets/decrypt.rs
bottlecap/src/telemetry/events.rs
bottlecap/src/telemetry/listener.rs

Lambda SnapStart doesn't provide AWS access credentials to prevent them from being cached during the snapshot creation process.
We have two options, we can delay resolving credentials into the invoke phase (probably don't wanna do that for performance reasons where users rely on the additional vCPU power during init), or we can use the credential API to grab creds during init and use them.
Since we never re-use credentials, this works fine for us. It should only incur overhead during snapshot creation, which is a control plane operation anyway.
Screenshot of the decrypted secrets w/ snapshot (long since expired):
(can't wait for a bot to try these old expired creds)

feat: Support snapstart's vended credentials

---

bottlecap/Cargo.lock
bottlecap/Cargo.toml
bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/logs/aggregator.rs
bottlecap/src/traces/aggregator.rs
bottlecap/src/traces/mod.rs
bottlecap/src/traces/stats_aggregator.rs
bottlecap/src/traces/stats_flusher.rs
bottlecap/src/traces/trace_agent.rs
bottlecap/src/traces/trace_aggregator.rs
bottlecap/src/traces/trace_flusher.rs
bottlecap/src/traces/trace_processor.rs

Adds aggregators for Traces and Stats.
Large trace payloads are being dropped, because they're rejected by the backend.
Also [SVLS-6250](https://datadoghq.atlassian.net/browse/SVLS-6250)
- Added unit tests
- Tested in an AWS Lambda with a heavy amount of incoming traces
[SVLS-6250]: https://datadoghq.atlassian.net/browse/SVLS-6250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add an Aggregator for Traces and Stats

---

bottlecap/src/traces/stats_aggregator.rs
bottlecap/src/traces/trace_aggregator.rs

Removes allocating memory for the buffer batch
Since the buffer is set as:
- `SendData` for traces
- `ClientStatsPayload` for stats
I'm allocating the buffer with the max content size in bytes, so it's around 3 million allocations of the object, instead of actual bytes.

fix: do not allocate memory for buffer

---

scripts/Dockerfile.alpine.build
scripts/Dockerfile.build

See vuln scan failure https://github.com/DataDog/datadog-lambda-extension/actions/runs/13190321135/job/36862794785. Fixed by upgrading go from v1.23.2 to v1.23.6.

Bump go version to 1.23.6 to address CVE-2025-22866.

---

bottlecap/src/lifecycle/invocation/processor.rs

This reverts commit b6ed2db9fe7c74b1696259efd2838d1015372451.

Revert "feat: Extract sampling priority from tracer and apply to new lambda span"

---

bottlecap/src/proc/constants.rs
bottlecap/src/proc/mod.rs

Modifies the network check to also look at `vint_runtime` which is present in some runtimes instead of the `vinternal_1` device
seems strange because node20 self monitoring has these metrics?
debug logs from my node20 test function:
```
DD_EXTENSION | DEBUG | astuyve line "Inter-|   Receive                                                |  Transmit"
DD_EXTENSION | DEBUG | astuyve line " face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed"
DD_EXTENSION | DEBUG | astuyve line "    lo:  304049     606    0    0    0     0          0         0   304049     606    0    0    0     0       0          0"
DD_EXTENSION | DEBUG | astuyve line "vint_runtime: 1333674    1153    0    0    0     0          0         0   507891    1170 …
```

Check vint_runtime as well as vinternal_1 for network metrics

---

.github/workflows/release-serverless-init.yml
scripts/Dockerfile.serverless-init.build

There is an issue with the qemu action that results in build failures. Pinning to `tonistiigi/binfmt:qemu-v7.0.0-28` fixes the issue.

Update QEMU step in workflow

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/config/mod.rs

For FIPs compliance, we're falling back to the Go agent when the Lambda is in a govcloud region.
Tested manually, we do fall back as expected on gov regions:
```
{
"DD_EXTENSION_FALLBACK_REASON": "gov_region"
}
```

Fallback on gov regions

---

.github/workflows/release-serverless-init.yml
scripts/Dockerfile.build

Switched back to the QEMU action instead of pinning the version. 
It was fixed in the [latest version](https://github.com/tonistiigi/binfmt/issues/215#issuecomment-2689340770)

Use QEMU action to fix builds

---

.gitignore
.gitlab/datasources/flavors.yaml
.gitlab/scripts/build_layer.sh
.gitlab/scripts/compile_bottlecap.sh
.gitlab/scripts/compile_go_agent.sh
.gitlab/templates/pipeline.yaml.tpl
images/Dockerfile.bottlecap.dev
images/Dockerfile.build_layer
scripts/build_bottlecap_layer.sh
scripts/publish_bottlecap_sandbox.sh

Fixes local bottlecap dev scripts
Modifying `SUFFIX` to `FILE_SUFFIX` to make it more clear.
- tested manually by building with
```sh
ARCHITECTURE=arm64 SUFFIX=Jordan ./scripts/publish_bottlecap_sandbox.sh
```
and
```sh
ARCHITECTURE=arm64 ./scripts/build_bottlecap_layer.sh
```
- pipelines pass
I tried removing `suffix` overall in the `datasources/flavors.yaml` but it just complicates things more, I still think we shouldnt have it tho.

fix: update pipeline and dev scripts

---

.gitlab/Dockerfile
images/Dockerfile.build_layer
images/Dockerfile.go_agent.alpine.compile
images/Dockerfile.go_agent.compile

Fixes UPX compression to use latest `v5.0.0`
Previous one wasn't performant enough for cross-architecture compression
- Install UPX from GitHub in layer builder
- Remove compression on Go compilation
#Tests
- Tested manually in AWS Lambda by running scripts locally

chore: fix upx compression

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/tags/lambda/tags.rs
scripts/build_binary_and_layer_dockerized.sh

Printing a debug line like
```
DD_EXTENSION | DEBUG | Starting Datadog Extension 71
```
at start

add start info message

---

.github/workflows/serverless-vuln-scan.yml

Serverless Vulnerability Scan workflow is failing on the build step due to a segmentation fault error. Adding the latest version of the qemu setup Github job resolves this error.
Related to fix in datadog-agent: https://github.com/DataDog/datadog-agent/pull/34583
https://github.com/DataDog/datadog-lambda-extension/actions/runs/13665471225/job/38205999907
```
#14 13.87 Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
#14 13.95 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#14 14.35 Segmentation fault (core dumped)
#14 14.41 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#14 14.80 Segmentation fault (core dumped)
#14 14.80 dpkg: error processing package libc-bin (--configure):
#14 14.80  installed libc-bin package post-installation script …
```

Add qemu setup to serverless vuln scan workflow

---

bottlecap/src/bin/bottlecap/main.rs

In the case of a function running once every few hours, we may not block for the platform.report event.
this PR modifies the loop to wait for this event so we set some enhanced metrics after a single function execution.

feat: Shutdown blocks for report

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/lifecycle/invocation/processor.rs
bottlecap/src/metrics/enhanced/lambda.rs

Adds the produced bytes enhanced metric received on PlatformRuntimeDone

Produced bytes enhanced metric

---

bottlecap/src/lifecycle/flush_control.rs

fixes an issue where flush strategy `END` without an interval could cause an overflow error

fix: max duration 15 minutes

---

bottlecap/src/lifecycle/invocation/triggers/step_function_event.rs
bottlecap/src/traces/propagation/text_map_propagator.rs
bottlecap/tests/payloads/step_function_lambda_root_event.json
bottlecap/tests/payloads/step_function_lambda_root_legacy_event.json
bottlecap/tests/payloads/step_function_nested_event.json
bottlecap/tests/payloads/step_function_nested_legacy_event.json

Updates the creation of trace context from a Step Function execution's context object to...
1. Make use of `State.RetryCount` and `Execution.RedriveCount` for inferable parent ID generation in a backwards compatible manner (related to https://github.com/DataDog/datadog-lambda-python/pull/559)
2. Support the new trace context propagation for multi-level trace merging. These are cases where we're receiving a Step Function event but that Step Function has another parent service which can be either a Lambda or another Step Function (related https://github.com/DataDog/datadog-lambda-python/pull/537)
Parity of https://github.com/DataDog/datadog-agent/pull/34264
1. Using these new values for parent ID generation will prevent collisions with "retry spans" which are Step Function spans that parent …

feat(bottlecap): Update Step Functions trace extraction

---

bottlecap/src/config/mod.rs

Fixes #606, also accounts for DD_SERVICE which, in unusual but possible circumstances, could be an int

feat: parse env and service as strings or ints

---

bottlecap/src/bin/bottlecap/main.rs

Adds a debug message with our init duration for the extension specifically, measured by the time main begins to the time we call `/next`
aids in debugging/disambiguation cases

feat: Add readiness debug log

---

bottlecap/Cargo.lock
bottlecap/Cargo.toml
bottlecap/src/bin/bottlecap/main.rs
bottlecap/tests/metrics_integration_test.rs

fixes: #612
also includes a faster tag sorter for startup

Update dogstatsd to use retry pushed to client

---

scripts/datadog_wrapper

Change the way we set .NET environment variables in `datadog_wrapper`, so we only set them if they are not already set. This prevents the script from overriding env vars set by the user.
For example, setting `CORECLR_ENABLE_PROFILING=0` does not disable the tracer, because `datadog_wrapper` then sets `CORECLR_ENABLE_PROFILING=1`. See https://github.com/DataDog/dd-trace-dotnet-aws-lambda-layer/issues/14.

[dotnet] don't override env vars if set by user

---

scripts/datadog_wrapper

~Stacked on #623. Merged that PR first.~ ✅
By default, disable a few unused features in `dd-trace-dotnet` to improve startup times and total execution times:
env var name | Description
-------------|------------
`DD_TRACE_STARTUP_LOGS=0` | skip generating the startup log entry (which writes to the file system)
`DD_CIVISIBILITY_ENABLED=0` | explicitly disable CI Visibility to skip it's auto-detection logic

[dotnet] disable some features by default

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/lifecycle/invocation/processor.rs
bottlecap/src/traces/trace_agent.rs
bottlecap/src/traces/trace_processor.rs

Removes the Mutex Lock on `ContextBuffer`
We were using `ContextBuffer` to share `tracer_span` so that we can enrich the top level span generated by the Extension. Instead, we now share the already existing `InvocationProcessor` lock which allows us to set the `tracer_span` on the given context.
Works as before.
There is a known issue which only makes it work on cold start spans, this was also something that appeared on the previous approach.

chore: remove mutex lock for `ContextBuffer` 

---

scripts/Dockerfile.alpine.build
scripts/Dockerfile.build
scripts/Dockerfile.race.build

This partially reverts commit 9a3e8ada9ea0dbbc4e2fa426947f32221b82629e. [#633](https://github.com/DataDog/datadog-lambda-extension/pull/633)
Datadog Agent Serverless Integration Tests, Vulnerability Scan, and Serverless-Init Release Github Workflows are failing due to not being able to pull the mirrored Datadog images.
Only the images in `scripts`, which are used in Github Workflows are reverted as part of this PR. Images in `images` used in GitLab CI/CD for Bottlecap will continue to use the mirrored Datadog images.
https://github.com/DataDog/datadog-agent/actions/runs/14197727594/job/39776831216
```
ERROR: failed to solve: DeadlineExceeded: DeadlineExceeded: DeadlineExceeded: DeadlineExceeded: failed to resolve source metadata for registry.ddbuild.io/images/mirror/ubuntu:22.04: failed …
```

Partially Revert Mirrored Images

---

scripts/Dockerfile.alpine.build
scripts/Dockerfile.build
scripts/Dockerfile.race.build

Vulnerability scan failure: https://github.com/DataDog/datadog-lambda-extension/actions/runs/14369347938/job/40331528479
https://datadoghq.atlassian.net/browse/SVLS-6593
Built rc image (1.6.1-rc1, 1.6.1-rc1-alpine), ran `trivy image` command against images to confirm vulnerability was addressed. Deployed to GCR self monitoring

bump go to 1.23.8 for serverless-init

---

bottlecap/src/lifecycle/invocation/processor.rs

do not override trace id or span id if they were already set during

---

bottlecap/src/bin/bottlecap/main.rs

We don't need any configuration options in order to register the extension, so make that request first.

feat: Register first in main

---

bottlecap/src/lifecycle/invocation/span_inferrer.rs
bottlecap/src/lifecycle/invocation/triggers/api_gateway_websocket_event.rs
bottlecap/src/lifecycle/invocation/triggers/mod.rs
bottlecap/tests/payloads/api_gateway_websocket_connect_event.json
bottlecap/tests/payloads/api_gateway_websocket_disconnect_event.json
bottlecap/tests/payloads/api_gateway_websocket_message_event.json

Adds inferred spans for API Gateway Websocket Events (`connect`, `message`, and `disconnect`).
Copied a lot of logic (for tags, span name/resource name, etc.) from the websocket inferred spans in https://github.com/DataDog/datadog-lambda-js/blob/9e67be3a05100ba85d825ed84219cf0a8271f9ec/src/trace/span-inferrer.ts#L88
_Full JSON of trace: https://pastebin.com/raw/1pdPqWh8_
_Full JSON of trace: https://pastebin.com/raw/0c229ts7_
_Full JSON of trace: https://pastebin.com/raw/JryvzpwP_

feat(bottlecap): add API Gateway Websocket inferred spans

---

bottlecap/src/config/env.rs
bottlecap/src/config/mod.rs
bottlecap/src/config/yaml.rs

Removes `FallbackConfig` and `FallbackYamlConfig` in favor of the existing configurations.
1. Using only the known places where we are going to fallback from the available configs.
2. Moved environment variables and yaml config to its own file for readability.
- Added fallbacks for OTLP (in preparation for that PR, allowed some fields to not fallback).

chore(config): parse config only twice 

---

bottlecap/src/lifecycle/invocation/triggers/api_gateway_websocket_event.rs
bottlecap/src/lifecycle/invocation/triggers/sqs_event.rs
bottlecap/tests/payloads/sns_sqs_binary_event.json

While investigating a trade propagation issue we realized there was no test for binary-encoded sns-sqs payloads, so I've added one.

fix: Add sns sqs binary tests

---

bottlecap/src/lifecycle/invocation/span_inferrer.rs

- In `span_inferrer.rs`, we were looking for `generated_span_context` first before looking for the inferred span's trace context.
- AWS Xray's trace context is extracted from the AWSTraceHeader in `extract_trace_context_from_aws_trace_header`. 
- Therefore, if the user has AWS Xray enabled, we would use that trace context rather than the inferred span's trace context, breaking trace propagation.
- The fix is simply swapping the order of the if statements: first look for inferred span's trace context, then look for trace context in the AWS trace header.
Before this change, trace propagation was broken when Xray was enabled:
After this change, trace propagation works as expected with Xray enabled:
The Datadog Java tracer injects trace context in the AWSTraceHeader for SQS, so I also …

fix: Extract trace context from inferred span when AWS Xray is enabled

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/config/env.rs
bottlecap/src/config/mod.rs

Fixes an issue where we didn't parse `DD_APM_REPLACE_TAGS` because the yaml block includes an additional `config` word after APM, which is not present in the env var.
As usual, env vars override config file settings

fix: Parse DD_APM_REPLACE_TAGS env var

---

bottlecap/src/config/env.rs
bottlecap/src/lifecycle/invocation/processor.rs

Fixes #648
For customers using very very fast/small lambda functions (usually just rust), there can be a small 1-2ms increase in runtime duration when collecing metrics like open file descriptors or tmp file usage.
We still enable these by default, but customers can now optionally disable them

feat: Optionally disable proc enhanced metrics

---

bottlecap/src/lifecycle/invocation/span_inferrer.rs
bottlecap/src/lifecycle/invocation/triggers/mod.rs
bottlecap/src/lifecycle/invocation/triggers/msk_event.rs
bottlecap/tests/payloads/msk_event.json

Add inferred spans for MSK events. Since there are multiple records, possibly from multiple different topics, we just get the first item from the first topic and use that information to create the inferred span.
https://datadoghq.atlassian.net/browse/SVLS-6711

feat(bottlecap): add MSK inferred spans

---

bottlecap/src/traces/trace_agent.rs

Implement the Exception Replay endpoint. This ports over the endpoint from datadog-agent: https://github.com/DataDog/datadog-agent/blob/ca681197f983c9d6b508e4b40d4526bb9a02c4ce/pkg/trace/api/endpoints.go#L140-L143
[Exception Replay](https://www.datadoghq.com/blog/exception-replay-datadog/) is a tracer feature that allows users to see local variables in the Datadog UI, kind of like a in a debugger in an IDE.
Exception replay can be enabled in the tracer with the `DD_EXCEPTION_REPLAY_ENABLED=true` environment variable. Currently, it's only supported in Python (in Lambda), but will be coming to Java and .NET very soon. Node will follow after.
Manual testing:
- This is the only change needed in the lambda extension; any other changes to support Java or .NET will take place in dd-trace-java …

(feat): Exception Replay endpoint

---

bottlecap/src/config/env.rs
bottlecap/src/otlp/transform.rs

Removes usage of `DD_APM_IGNORE_RESOURCES` in the OTEL span transform.
1. The implementation was incorrect and shouldn't check for resources to ignore in the transformation step.
2. It was not properly used in the `apm_config` for YAML files.
- Follow up PR to implement `APM_IGNORE_RESOURCES` properly in the Trace Agent.
Learn about ignoring resources: https://docs.datadoghq.com/tracing/guide/ignoring_apm_resources/?tab=datadogyaml#ignoring-based-on-resources
`DD_APM_IGNORE_RESOURCES` is specified as:
```
A list of regular expressions can be provided to exclude certain traces based on their resource name.
All entries must be surrounded by double quotes and separated by commas.
```
A correct usage would be:
```env
DD_APM_IGNORE_RESOURCES="(GET|POST) /healthcheck,API::NotesController#index" …
```

fix(config): remove `apm_ignore_resources` check in OTEL

---

bottlecap/src/lifecycle/invocation/triggers/api_gateway_websocket_event.rs

Fixes `http.url` for API Gateway WebSockets to include the protocol
It was done everywhere else but here

fix(inferred spans): add protocol for api gateway web sockets http url

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/config/mod.rs
bottlecap/src/config/yaml.rs
bottlecap/src/otlp/mod.rs

Ensures that OTLP agent is only enabled when the `otlp_config_receiver_protocols_http_endpoint` is set, and when `otlp_config_traces_enabled` is `true`
#678 
OTEL agent should only spin up when receiver protocols endpoint is set, so this was a miss on my side.

fix(config): fix otlp trace agent to start when right configuration is set

---

bottlecap/src/config/env.rs

A little goofy because we use this to determine when/how to move over to continuous flushing, but the gist is that our invocation context tracks the start time of each invocation. Because it's all local to a single sandbox, this means that the time diff between invocations includes post runtime duration, so it's very common to have 20 invocations greater than 10s if there are even a couple of periodic/end flushes in there.
This customizable with `DD_FLUSH_TIMEOUT` so if people want to set it to a very short timeout, they are able to.

fix: bump flush_timeout default

---

bottlecap/src/config/env.rs
bottlecap/src/config/mod.rs
bottlecap/src/config/yaml.rs
bottlecap/src/proxy/mod.rs

i am currently working on Appsec enablement inside the `datadog-lambda-python` tracer and I have noticed that the extension unnecessarily falls back to the go extension when Appsec is enabled at the tracer level.
Appsec inside the extension should only be managed by the `DD_SERVERLESS_APPSEC_ENABLED` env var. 
The `DD_APPSEC_ENABLED` one is reserved for tracer enablement.
Remove the conflicting `appsec_enabled` configuration option.
CC @Julio-Guerra

fix(appsec): remove conflicting appsec_enabled configuration

---

bottlecap/src/otlp/transform.rs

- Fixes environment mapping logic that created a false choice between env field mapping and service/operation name mapping
- Moves OTEL deployment.environment → Datadog env field mapping to work alongside service/operation name mapping when DD_OTLP_CONFIG_IGNORE_MISSING_DATADOG_FIELDS=false (default)
- Resolves issue where spans show env="none" despite correct OTEL resource attributes
Previously, environment mapping from OTEL `deployment.environment` to Datadog `env` field only worked when `DD_OTLP_CONFIG_IGNORE_MISSING_DATADOG_FIELDS=true`, but service/operation name mapping only worked when this flag was false (default). This created a false choice where users had to choose between environment mapping OR service/operation name mapping.
- Moved environment mapping logic from the …

fix: move env mapping from ignore_missing_datadog_fields=true to false block

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/lib.rs
bottlecap/src/otlp/agent.rs
bottlecap/src/telemetry/listener.rs

Moves the Telemetry API listener from hyper to axum
Let axum handle connections and errors gracefully

chore(telemetry-api): move listener to axum

---

bottlecap/src/config/mod.rs
bottlecap/src/lifecycle/invocation/mod.rs
bottlecap/src/lifecycle/invocation/processor.rs
bottlecap/src/lifecycle/invocation/triggers/event_bridge_event.rs
bottlecap/src/lifecycle/invocation/triggers/lambda_function_url_event.rs
bottlecap/src/lifecycle/invocation/triggers/msk_event.rs
bottlecap/src/lifecycle/invocation/triggers/sqs_event.rs
bottlecap/src/otlp/agent.rs
bottlecap/src/proc/mod.rs
bottlecap/src/proxy/interceptor.rs
bottlecap/src/traces/propagation/text_map_propagator.rs
bottlecap/src/traces/stats_aggregator.rs
rust-toolchain.toml

1. In `rust-toolchain.toml`, upgrade Rust version from `1.81.0` to `1.84.1`.
2. Fix/mute clippy errors caused by the upgrade
- some errors require non-trivial code changes, so I muted them for now and added a TODO to fix them in separate PRs.
`libdatadog` now uses `1.84.1` https://github.com/DataDog/libdatadog/blame/main/Cargo.toml#L62
To test changes on `libdatadog`, I need to change the Rust version in `datadog-lambda-extension` to 1.84.1 as well.
Making this a separate PR:
1. so it's easier to test multiple PRs that depend on changes on `libdatadog` in parallel after I merge this PR to main.
4. because this PR also involves lots of code changes needed to make clippy happy

chore: upgrade rust version for toolchain to 1.84.1

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/http.rs
bottlecap/src/logs/flusher.rs
bottlecap/src/traces/mod.rs
bottlecap/src/traces/proxy_aggregator.rs
bottlecap/src/traces/proxy_flusher.rs
bottlecap/src/traces/trace_agent.rs

Creates an aggregator and flusher for APM proxy data.
With the introduction of #684, the Extension is way faster to continue invocations, I think this could have affected how data is aggregated for this various APM products in which we were just sending the request to intake as soon as it arrives.
Now, we aggregate it and respect the flushing pattern and algorithm.
1. Profiling:
2. LLMObs:
3. DSM:
tbd
4. Live Debugger:

feat(apm): aggregate and flush data accordingly for DSM, Profiling, LLMObs, and Live Debugger

---

.cargo/config.toml

chore(cargo): use `dd-rust-license-tool` instead of `bundle-licenses`

---

.gitlab/datasources/flavors.yaml

AAP requires installing binaries from `libddwaf` which in turn increase the layer size by a couple MB

chore(gitlab): increase layer size for aap

---

bottlecap/src/traces/trace_aggregator.rs

Change trace payload size limit from 3.2 MiB (3.2 * 1024 * 1024) to 3.2 MB (3.2 * 1000 * 1000) because that's more commonly used in the codebase.
https://github.com/search?q=org%3ADataDog%203200000&type=code

chore: Change trace payload size limit from 3.2 MiB to 3.2 MB

---

bottlecap/src/proc/constants.rs
bottlecap/src/tags/lambda/tags.rs

We fail to parse the runtime when it is `provided.al2` or `provided.al2023`. I don't though what's the impact though, because in Datadog logs, the runtime tag is shown correctly even if I removed all the env vars related to runtime.
Fix the problem by changing the path from `/etc` to `/etc/os-release`.
Thanks @shreyamalpani for the idea about the fix.
Failed to parse the runtime
Works for both al2 and al2023

fix: Fix parsing provided.al runtime by reading /etc/os-release

---

images/Dockerfile.go_agent.alpine.compile
images/Dockerfile.go_agent.compile
scripts/Dockerfile.alpine.build
scripts/Dockerfile.build
scripts/Dockerfile.race.build

vulnerability: upgrade `go` to `1.24.6`

---

bottlecap/src/logs/flusher.rs

When logs fail to be sent to Datadog, the extension prints an error:
> No more retries as the access was rejected
which I think can be more clear.
Change the error message to:
> Failed to send logs to datadog because access was rejected. Is the API key invalid?

chore: Update error message when fail to send log

---

images/Dockerfile.extension_image

`.dockerignore` was introduced which ignores layers, so we cannot use `COPY` because it fails when building the final image which will land on ECR
Images not building

fix(images): build to also use mount

---

bottlecap/Cargo.lock
bottlecap/Cargo.toml
bottlecap/LICENSE-3rdparty.csv

Uses latest version of `libddwaf` in order to dynamically load the binary
Avoid having performance regression for all customers

fix(aap): use `dynamic` feature in `libddwaf`

---

bottlecap/src/config/mod.rs
bottlecap/src/proc/constants.rs
bottlecap/src/proc/mod.rs
scripts/datadog_wrapper

Fallbacks on .NET runtimes by checking the `dotnet` binary presence in `/var/lang/bin`
Provide a fallback + appsec for .NET until runtime is fixed
Reverts #803

fix(aap): fallback on .NET runtimes

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/http.rs
bottlecap/src/lifecycle/invocation/context.rs
bottlecap/src/lifecycle/invocation/processor.rs
bottlecap/src/lifecycle/invocation/span_inferrer.rs
bottlecap/src/lifecycle/listener.rs
bottlecap/src/lwa/mod.rs
bottlecap/src/proxy/interceptor.rs
bottlecap/src/traces/propagation/mod.rs

Decouples Span Inferrer methods by refactoring them
Help remove lock on hot-path, delegate lock for task in universal instrumentation start, while maintaining span context extraction for tracer to use
It's a long refactor 😴

fix(inferred-spans): refactor and decouple span inferrer

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/http.rs
bottlecap/src/lifecycle/invocation/context.rs
bottlecap/src/lifecycle/invocation/processor.rs
bottlecap/src/lifecycle/invocation/span_inferrer.rs
bottlecap/src/lifecycle/listener.rs
bottlecap/src/lwa/mod.rs
bottlecap/src/proxy/interceptor.rs
bottlecap/src/traces/propagation/mod.rs

Make Lifecycle Listener for Universal Instrumentation to spawn tasks to process data
There is no need to await for it to finish in order to continue, also [SVLS-7464](https://datadoghq.atlassian.net/browse/SVLS-7464)
Still trying to figure out how to handle invocation end
[SVLS-7464]: https://datadoghq.atlassian.net/browse/SVLS-7464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(lifecycle): spawn tasks on listener

---

bottlecap/src/config/env.rs
bottlecap/src/config/mod.rs
bottlecap/src/config/yaml.rs
bottlecap/src/tags/lambda/tags.rs

Adds a feature flag `DD_COMPUTE_TRACE_STATS`.
- If true, trace stats will be computed from the extension side. In this case, we set `_dd.compute_stats` to `0`, so trace stats won't be computed on the backend.
- If false, trace stats will NOT be computed from the extension side. In this case, we set `_dd.compute_stats` to `1`, so trace stats will be computed on the backend.
- Defaults to false for now, so `_dd.compute_stats` still defaults to `1`, i.e. default behavior is not changed.
- After we fully support computing trace stats on extension side, I will change the default to true then delete the flag.
Jira: https://datadoghq.atlassian.net/browse/SVLS-7593

feat: [Trace Stats] Add feature flag DD_COMPUTE_TRACE_STATS

---

bottlecap/src/appsec/processor/context.rs

These produce excessive log spam in customer accounts, for conditions they may not be able to generally address (either because the cause is outside of their control, or because they decided the trade-off was acceptable).
The alternative would be allowing granuar configuration of log level limits for each module, which would be a significantly more involved change.
This also reverts to a behavior that is closer to that of the Go version, which was silently ignoring these conditions for the most part.
Fixes #840

fix(aap): lower severity of several warnings

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/secrets/decrypt.rs

When a Lambda (1) uses snap start, and (2) specifies Datadog API key using `DD_API_KEY_SECRET_ARN`, the extension will encounter a deadlock. For a `RwLock`, the extension first gets a read lock:
https://github.com/DataDog/datadog-lambda-extension/blob/daf633dd003447d78261e7c371838b5af21073a1/bottlecap/src/secrets/decrypt.rs#L45
then tries to get a write lock:
https://github.com/DataDog/datadog-lambda-extension/blob/daf633dd003447d78261e7c371838b5af21073a1/bottlecap/src/secrets/decrypt.rs#L65
which never finishes. This causes the function to time out.
This bug was introduced in https://github.com/DataDog/datadog-lambda-extension/pull/717.
Fix this bug by removing the `RwLock` usage. `AwsCredential` is only created and used once in `resolve_secrets()`, and `resolve_secrets()` is only called …

fix: Fix deadlock when snap start and using secret for api key

---

bottlecap/Cargo.toml

fix: strip debug symbols

---

bottlecap/src/traces/stats_concentrator.rs
bottlecap/src/traces/stats_concentrator_service.rs
bottlecap/src/traces/stats_generator.rs

Set these fields on trace stats:
- `lang`
- `tracer_version`
- `runtime_id`
Jira: https://datadoghq.atlassian.net/browse/SVLS-7593

feat: [Trace Stats] Handle tracer lang, tracer version and runtime_id

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/traces/stats_aggregator.rs
bottlecap/src/traces/stats_concentrator.rs
bottlecap/src/traces/stats_concentrator_service.rs
bottlecap/src/traces/stats_generator.rs

1. For `hostname` field: pass in `tags_provider` and use it to get function arn. Refer to existing code about:
1. how to get function arn:
https://github.com/DataDog/datadog-lambda-extension/blob/3f90d2bb09b4213e3b683dc84333e48faeddba3a/bottlecap/src/logs/lambda/processor.rs#L65
2. use function arn as hostname:
https://github.com/DataDog/datadog-lambda-extension/blob/3f90d2bb09b4213e3b683dc84333e48faeddba3a/bottlecap/src/logs/lambda/processor.rs#L259
2. Change the default value of `env` to `unknown-env`, following this RFC: https://docs.google.com/document/d/1NmGVxNyd9o8UQ7AvFKjOVq5tBDN6GN8jeQmvyBUnkrQ
Jira: https://datadoghq.atlassian.net/browse/SVLS-7593

feat: [Trace Stats] Handle hostname and env

---

bottlecap/src/config/env.rs
bottlecap/src/config/mod.rs
bottlecap/src/config/yaml.rs
bottlecap/src/otlp/agent.rs
bottlecap/src/tags/lambda/tags.rs
bottlecap/src/traces/trace_processor.rs

As @apiarian-datadog suggested in https://github.com/DataDog/datadog-lambda-extension/pull/841#discussion_r2376111825, rename the feature flag `DD_COMPUTE_TRACE_STATS` to `DD_COMPUTE_TRACE_STATS_ON_EXTENSION` for clarity.
Jira: https://datadoghq.atlassian.net/browse/SVLS-7593

chore: [Trace Stats] Rename env var DD_COMPUTE_TRACE_STATS

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/extension/mod.rs

Allows registering extension with name from parameter
Want to reuse it for another extension

chore(extension): allow register with name

---

bottlecap/src/secrets/decrypt.rs
bottlecap/src/traces/stats_flusher.rs
bottlecap/src/traces/trace_flusher.rs

Right now we have debug log like `Flushing traces took 50ms`. This PR adds a space between `50` and `ms` so it's easier to process the log. For example, we can use `echo 'Flushing traces took 50 ms' | awk '{print $4}'` to extract the `50`.

chore: Add a space in debug log for duration

---

bottlecap/src/bin/bottlecap/main.rs
bottlecap/src/event_bus/mod.rs
bottlecap/src/extension/telemetry/events.rs
bottlecap/src/extension/telemetry/listener.rs
bottlecap/src/logs/agent.rs
bottlecap/src/traces/trace_agent.rs
bottlecap/tests/logs_integration_test.rs

The Telemetry API needs to signal the main event loop that it stopped processing events. The order of how this operations occurred could have been busted before. This fixes it and moves the code around so the cancel token can trigger the Tombstone signal.
Reduces time spent on shutdown when processing
Also makes the Tombstone event to be a main event as opposed to a Telemetry API event

fix: tombstone event to be sent properly
