README.md
Related to https://github.com/DataDog/documentation/pull/13574. Consolidate serverless monitoring configuration instructions in one place.
=> Configuration instructions in one place

scripts/Dockerfile.alpine.build, scripts/Dockerfile.build, scripts/build_binary_and_layer_dockerized.sh, scripts/build_cloud_run.sh
This PR adds alpine support for CloudRun
Note: In a next PR, the 3 Dockerfiles could be better organized (classic, alpine, race) since they share some common code
=> Support alpine for CloudRun

scripts/Dockerfile
I built the image locally and unzipped:
=> Add datadog_wrapper to the docker image

.github/workflows/codeql-analysis.yml, .github/workflows/redirect_issues.yml
=> bump github actions

.github/workflows/deploy-sandbox.yml, build-tools/src/commands/deploy_command.rs
Add region choice option (dev, RC, all)
Skip list-region if `region !=all`
=> Add region option

local_tests/build-docker-runtime.sh, scripts/publish_layers.sh, scripts/publish_sandbox.sh
`serverless-sandbox-account` is now standard for our self monitoring applications.
=> feat: Use new serverless account

scripts/Dockerfile.build, scripts/Dockerfile.race.build, scripts_v2/Dockerfile.build
=> bump go to v1.19

.github/workflows/deploy-sandbox.yml
=> add masks for numbers to prevent output

scripts/Dockerfile.alpine.build, scripts/Dockerfile.build, scripts/Dockerfile.race.build, scripts/build_binary_and_layer_dockerized.sh, scripts_v2/Dockerfile.build
Reverts DataDog/datadog-lambda-extension#115
=> Revert "Revert "Build binaries with otlp enabled.""

local_tests/build-docker-runtime.sh, scripts/publish_prod.sh
Uses sso profiles for publishing to prod + the local invocation testing
=> [serverless] Update aws-vault usage to sso

scripts/Dockerfile.alpine, scripts/Dockerfile.alpine.build, scripts/build_and_push_docker_image.sh, scripts/build_binary_and_layer_dockerized.sh
Support building + releasing alpine lambda extension images
This builds both amd64 & arm64 alpine images. The images will be tagged `latest-alpine` and `{supplied_version}-alpine`
=> Support building extension images for alpine

scripts/publish_prod.sh
Updated Lambda Extension release script to use SSO profile for GovCloud
https://datadoghq.atlassian.net/browse/SVLS-4794
=> Update Lambda Extension Release Script to Use SSO Profile for GovCloud

bottlecap/src/config.rs
Updates the config precedence to be `Environment > YAML`.
Keep consistency with the Go Agent.
=> feat(bottlecap): Update config precedence

bottlecap/Cargo.lock, bottlecap/Cargo.toml
Cleans `Cargo.toml` to disable default features for every package.
=> chore(bottlecap): remove unnecessary dependencies

bottlecap/src/metrics/aggregator.rs
- removing some extra code
- decouple Type from the aggregator
- remove redundant type in entry
- remove wrapper types over tuples for counter/gauge/ddsketches. There is already 3+ structs for them
=> Refactor metricvalue

bottlecap/src/telemetry/listener.rs
Noisey log without much data, so we can drop this.
=> fix: drop noisey log

bottlecap/src/bin/bottlecap/main.rs, bottlecap/src/logs/aggregator.rs, bottlecap/src/logs/lambda/processor.rs, bottlecap/src/logs/processor.rs, bottlecap/src/metrics/aggregator.rs, bottlecap/src/metrics/enhanced/lambda.rs, bottlecap/src/metrics/metric.rs, bottlecap/src/secrets/decrypt.rs, bottlecap/src/tags/lambda/tags.rs, bottlecap/src/telemetry/events.rs, bottlecap/src/telemetry/listener.rs, bottlecap/src/traces/trace_processor.rs
- remove all unwraps from non test code
- remove all warnings from clippy
- if active loops fail, run the noop loop to call /next
=> Svls 4910 make sure next on crash

bottlecap/src/bin/bottlecap/main.rs, bottlecap/src/metrics/datadog.rs, bottlecap/src/metrics/dogstatsd.rs, bottlecap/src/traces/trace_agent.rs
Replace info! with debug! and use tracing lib instead of logging.
=> feat: Remove info, use debug

bottlecap/src/bin/bottlecap/main.rs, bottlecap/src/config/mod.rs, bottlecap/src/metrics/enhanced/lambda.rs
Some people will turn this off but still want logs, this change allows that.
=> feat: honor enhanced metrics bool

bottlecap/src/config/log_level.rs
Info is just a bit noisy. I think by default warn is good here.
=> feat: warn by default

bottlecap/src/bin/bottlecap/main.rs, bottlecap/src/metrics/dogstatsd.rs, bottlecap/src/metrics/metric.rs
TODO:
- add test for multi-line metric
- Add test for single metric
- Talk with George on SMP
=> feat: multi-metric support

bottlecap/src/config/flush_strategy.rs, bottlecap/src/lifecycle/flush_control.rs, bottlecap/src/metrics/dogstatsd.rs, bottlecap/src/metrics/metric.rs
Adding test, verified with Single Machine Performance beta tester that the metrics goes through, it is just an error log for an empty newline
=> Fix dogstatsd multiline

scripts/Dockerfile.bottlecap.alpine.build, scripts/Dockerfile.bottlecap.build, scripts/Dockerfile.bottlecap.dev
=> fix(bottlecap): update build images

.github/workflows/serverless-vuln-scan.yml
In addition to doing a vulnerability scan on the latest extension code from main, also scane the most recently released extension images.
=> Scan latest releases for vulnerabilities.

bottlecap/src/tags/lambda/tags.rs
=> feat: set 63-next version in prep for release

bottlecap/src/tags/lambda/tags.rs
Upgrades the internal version to 66
=> chore: upgrade version to 66

.gitlab-ci.yml
Upgrade the lambda extension upgrade lot of security issue.
=> fix: update placeholder value for datadog-agent in gitlab pipeline

.gitlab/datasources/regions.yaml
Adds the new regions from Mexico and Thailand
=> chore(gitlab): add `mx-central-1` and `ap-southeast-7` regions

bottlecap/Cargo.lock, bottlecap/Cargo.toml
Bumps dsdrs PR to include the fix for dotnet's FD leak
=> feat: Bump dogstatsd with FD leak fix

.gitlab/scripts/check_layer_size.sh, scripts/Dockerfile.alpine.build, scripts/Dockerfile.bottlecap.alpine.build, scripts/Dockerfile.bottlecap.build, scripts/Dockerfile.bottlecap.dev
Using default compression, it goes 39mb->14mb
We agreed on using the fastest one, which will bring 39mb->19mb
https://github.com/upx/upx
=> Add exe compression upx

bottlecap/Cargo.lock, bottlecap/Cargo.toml, bottlecap/src/logs/aggregator.rs, bottlecap/src/logs/flusher.rs
- Remove clippy warnings
- Cleaner code
- Use futures instead of `JoinSet`
Refactor
=> chore: refactor logs flusher

bottlecap/src/lifecycle/flush_control.rs
Fixes an issue where manualy periodic flushes only happened at shutdown
=> fix: flush controller periodically case

bottlecap/src/tags/lambda/tags.rs
Really old comments I had from the initial POC.
=> chore: remove comments from tags

bottlecap/src/logs/lambda/processor.rs
The original code accounted for Lambda's own structured logging feature, but some users are using powertools or custom loggers and emitting one simple JSON log without the nested `message` param added by Lambda. The logic looking for Lambda's JSON logging version would inadvertently capture people using their own loggers but only parse/include the value of the `message` string, ignoring other attributes.
This handles both and includes a test.
You can see a custom logger + ddtags works in text mode:
As well as in JSON logging mode:
This also fixes an issue where the `level` wasn't being honored. It works now. Here it is for text mode:
And JSON:
Fixes #620
=> fix: handle non-nested 'message' values for structured logging without using Lambda's JSON logging feature

.gitlab/datasources/flavors.yaml, .gitlab/scripts/build_image.sh, .gitlab/scripts/build_private_image.sh, .gitlab/templates/pipeline.yaml.tpl
also removing the always-the-same flavor platform property
=> hotfix: unbreak the prod image build step

bottlecap/src/bin/bottlecap/main.rs
Reverts DataDog/datadog-lambda-extension#645
This breaks failover as we handle _that part_ in config
=> Revert "feat: Register first in main"

bottlecap/src/bin/bottlecap/main.rs, bottlecap/src/config/aws.rs, bottlecap/src/config/mod.rs, bottlecap/src/lifecycle/invocation/processor.rs, bottlecap/src/lifecycle/invocation/span_inferrer.rs, bottlecap/src/lifecycle/invocation/triggers/api_gateway_http_event.rs, bottlecap/src/lifecycle/invocation/triggers/api_gateway_rest_event.rs, bottlecap/src/lifecycle/invocation/triggers/api_gateway_websocket_event.rs, bottlecap/src/lifecycle/invocation/triggers/sqs_event.rs, bottlecap/src/lwa/proxy.rs, bottlecap/src/secrets/decrypt.rs
Refactors methods related to AWS config into its own module
Just cleaning and removing stuff from main – [SVLS-6686](https://datadoghq.atlassian.net/browse/SVLS-6686)
[SVLS-6686]: https://datadoghq.atlassian.net/browse/SVLS-6686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(config): create `aws` module

bottlecap/src/lifecycle/invocation/triggers/api_gateway_rest_event.rs, bottlecap/src/lifecycle/invocation/triggers/sqs_event.rs, bottlecap/src/logs/flusher.rs, bottlecap/src/tags/provider.rs, bottlecap/tests/logs_integration_test.rs
While reading through the codebase, I found a few opportunities for improvements.
This PR includes:
- Removal of unnecessary clone calls to reduce redundant allocations.
- Minor refactoring of variable names for better readability.
- Small adjustments to tests to align with the changes.
These changes are intended to improve performance and code clarity without altering any functionality.
=> chore: refactor remove unnecessary clones and minor cleanups

bottlecap/src/config/flush_strategy.rs
https://datadoghq.atlassian.net/browse/SVLS-6994
=> feat: Allow users to specify continuous strategy

bottlecap/src/traces/trace_agent.rs
Cleans the trace agent state handling
Easier to read in specific routes
Profiled an AWS Lambda in Python to ensure traces + profiles worked through different endpoint states
=> chore(trace-agent): clean state handling

bottlecap/src/traces/trace_agent.rs
https://datadoghq.atlassian.net/browse/SVLS-7324
Instrumentation Telemetry is not enabled for Lambda. This PR adds support for it.
Deployed for testing and checked logs:
`DD_EXTENSION | DEBUG | Trace Agent | Proxied request for instrumentation`
`DD_EXTENSION | DEBUG | Proxy Flusher | Successfully sent request in 340 ms to https://instrumentation-telemetry-intake.datadoghq.com/api/v2/apmtelemetry`
=> feat: Support proxying instrumentation telemetry API payloads

bottlecap/src/lifecycle/listener.rs
Migrates Lifecycle Listener to Axum
Better connection handling and [SVLS-7467](https://datadoghq.atlassian.net/browse/SVLS-7467)
[SVLS-7467]: https://datadoghq.atlassian.net/browse/SVLS-7467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: lifecycle listener to axum

images/Dockerfile.extension_image
=> fix: incorrectly built image for container based

bottlecap/src/appsec/processor/mod.rs
So as not to risk starving the async context.
=> chore(aap): use `tokio::sync::Mutex` instead of `std::sync::Mutex`

bottlecap/Cargo.lock, bottlecap/Cargo.toml, bottlecap/src/otlp/transform.rs
Names OpenTelemetry Database spans according to the convention outlined in https://opentelemetry.io/docs/specs/semconv/database/database-spans/
Addresses https://github.com/DataDog/datadog-lambda-extension/issues/808
=> fix: OTLP Database Span Naming

bottlecap/src/bin/bottlecap/main.rs, bottlecap/src/extension/mod.rs, bottlecap/src/extension/telemetry/mod.rs, bottlecap/src/logs/flusher.rs, bottlecap/src/logs/lambda/processor.rs, bottlecap/src/traces/proxy_flusher.rs, bottlecap/src/traces/trace_flusher.rs, bottlecap/src/traces/trace_processor.rs
Sometimes its very confusing to know what failed
=> chore: add prefix to some logs

bottlecap/src/bin/bottlecap/main.rs, bottlecap/src/otlp/agent.rs
Just cleans some of the main code when creating agents
=> chore: cleanup code for main agent creation
